/**
 * TOEIC 頻出単語データ
 *
 * 各エントリの構造:
 *   id       : 一意なID（学習履歴の保存キーになるので変更しないこと）
 *   word     : 英単語
 *   phonetic : 発音記号
 *   pos      : 品詞 (n. / v. / adj. / adv. / prep. / phr.)
 *   meaning  : 日本語の意味
 *   example  : 例文（英語）
 *   exampleJa: 例文（日本語訳）
 *   level    : 目標スコア帯 (600 / 730 / 860)
 *   category : 出題されやすい場面
 */
const WORD_DATA = [
  // ===== 人事・採用 =====
  { id: 1, word: 'applicant', phonetic: '/ˈæplɪkənt/', pos: 'n.', meaning: '応募者、志願者', example: 'All applicants must submit a resume by Friday.', exampleJa: '応募者は全員、金曜日までに履歴書を提出しなければならない。', level: 600, category: '人事・採用' },
  { id: 2, word: 'resume', phonetic: '/ˈrezʊmeɪ/', pos: 'n.', meaning: '履歴書', example: 'Please attach your resume to the email.', exampleJa: '履歴書をメールに添付してください。', level: 600, category: '人事・採用' },
  { id: 3, word: 'candidate', phonetic: '/ˈkændɪdət/', pos: 'n.', meaning: '候補者', example: 'We interviewed five candidates for the position.', exampleJa: 'その職に対して5人の候補者を面接した。', level: 600, category: '人事・採用' },
  { id: 4, word: 'recruit', phonetic: '/rɪˈkruːt/', pos: 'v.', meaning: '採用する、募集する', example: 'The company is recruiting engineers overseas.', exampleJa: 'その会社は海外でエンジニアを採用している。', level: 600, category: '人事・採用' },
  { id: 5, word: 'qualification', phonetic: '/ˌkwɒlɪfɪˈkeɪʃn/', pos: 'n.', meaning: '資格、適性', example: 'She has the qualifications required for the job.', exampleJa: '彼女はその仕事に必要な資格を持っている。', level: 600, category: '人事・採用' },
  { id: 6, word: 'promotion', phonetic: '/prəˈməʊʃn/', pos: 'n.', meaning: '昇進、販売促進', example: 'He received a promotion after five years.', exampleJa: '彼は5年後に昇進した。', level: 600, category: '人事・採用' },
  { id: 7, word: 'supervisor', phonetic: '/ˈsuːpəvaɪzə/', pos: 'n.', meaning: '上司、監督者', example: 'Report the issue to your supervisor immediately.', exampleJa: 'その問題はすぐに上司に報告してください。', level: 600, category: '人事・採用' },
  { id: 8, word: 'personnel', phonetic: '/ˌpɜːsəˈnel/', pos: 'n.', meaning: '職員、人事部', example: 'Contact the personnel department about your benefits.', exampleJa: '福利厚生については人事部に連絡してください。', level: 730, category: '人事・採用' },
  { id: 9, word: 'retirement', phonetic: '/rɪˈtaɪəmənt/', pos: 'n.', meaning: '退職、引退', example: 'A party was held to celebrate his retirement.', exampleJa: '彼の退職を祝うパーティーが開かれた。', level: 730, category: '人事・採用' },
  { id: 10, word: 'resign', phonetic: '/rɪˈzaɪn/', pos: 'v.', meaning: '辞職する', example: 'She resigned from her position last month.', exampleJa: '彼女は先月その職を辞任した。', level: 730, category: '人事・採用' },
  { id: 11, word: 'applicable', phonetic: '/əˈplɪkəbl/', pos: 'adj.', meaning: '適用できる、該当する', example: 'The discount is applicable to online orders only.', exampleJa: 'その割引はオンライン注文にのみ適用される。', level: 730, category: '人事・採用' },
  { id: 12, word: 'competent', phonetic: '/ˈkɒmpɪtənt/', pos: 'adj.', meaning: '有能な、適任の', example: 'He is a highly competent accountant.', exampleJa: '彼は非常に有能な会計士だ。', level: 860, category: '人事・採用' },
  { id: 13, word: 'tenure', phonetic: '/ˈtenjə/', pos: 'n.', meaning: '在職期間、終身在職権', example: 'During her tenure, sales doubled.', exampleJa: '彼女の在職期間中に売上は倍増した。', level: 860, category: '人事・採用' },
  { id: 14, word: 'incentive', phonetic: '/ɪnˈsentɪv/', pos: 'n.', meaning: '報奨、動機付け', example: 'Bonuses serve as an incentive for employees.', exampleJa: 'ボーナスは従業員への動機付けとなる。', level: 730, category: '人事・採用' },
  { id: 15, word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', pos: 'v.', meaning: '評価する', example: 'Managers evaluate staff performance twice a year.', exampleJa: '管理職は年2回、社員の業績を評価する。', level: 600, category: '人事・採用' },

  // ===== 会議・プレゼン =====
  { id: 16, word: 'agenda', phonetic: '/əˈdʒendə/', pos: 'n.', meaning: '議題、協議事項', example: 'The agenda for tomorrow’s meeting is attached.', exampleJa: '明日の会議の議題を添付しています。', level: 600, category: '会議・プレゼン' },
  { id: 17, word: 'attend', phonetic: '/əˈtend/', pos: 'v.', meaning: '出席する', example: 'Over 200 people attended the conference.', exampleJa: '200人以上がその会議に出席した。', level: 600, category: '会議・プレゼン' },
  { id: 18, word: 'postpone', phonetic: '/pəˈspəʊn/', pos: 'v.', meaning: '延期する', example: 'The meeting was postponed until next Monday.', exampleJa: '会議は次の月曜日まで延期された。', level: 600, category: '会議・プレゼン' },
  { id: 19, word: 'conference', phonetic: '/ˈkɒnfərəns/', pos: 'n.', meaning: '会議、学会', example: 'She will speak at the annual conference.', exampleJa: '彼女は年次会議で講演する予定だ。', level: 600, category: '会議・プレゼン' },
  { id: 20, word: 'presentation', phonetic: '/ˌprezənˈteɪʃn/', pos: 'n.', meaning: 'プレゼン、発表', example: 'His presentation lasted about thirty minutes.', exampleJa: '彼の発表は約30分続いた。', level: 600, category: '会議・プレゼン' },
  { id: 21, word: 'participant', phonetic: '/pɑːˈtɪsɪpənt/', pos: 'n.', meaning: '参加者', example: 'Each participant will receive a name tag.', exampleJa: '各参加者は名札を受け取ります。', level: 600, category: '会議・プレゼン' },
  { id: 22, word: 'handout', phonetic: '/ˈhændaʊt/', pos: 'n.', meaning: '配布資料', example: 'Please take a handout from the table.', exampleJa: 'テーブルから配布資料をお取りください。', level: 730, category: '会議・プレゼン' },
  { id: 23, word: 'keynote', phonetic: '/ˈkiːnəʊt/', pos: 'n.', meaning: '基調講演', example: 'The keynote speaker is a well-known economist.', exampleJa: '基調講演者は著名な経済学者だ。', level: 730, category: '会議・プレゼン' },
  { id: 24, word: 'brief', phonetic: '/briːf/', pos: 'adj./v.', meaning: '簡潔な／概要を説明する', example: 'He gave a brief overview of the project.', exampleJa: '彼はプロジェクトの簡単な概要を述べた。', level: 600, category: '会議・プレゼン' },
  { id: 25, word: 'convene', phonetic: '/kənˈviːn/', pos: 'v.', meaning: '招集する、集まる', example: 'The board will convene on Thursday.', exampleJa: '取締役会は木曜日に招集される。', level: 860, category: '会議・プレゼン' },
  { id: 26, word: 'adjourn', phonetic: '/əˈdʒɜːn/', pos: 'v.', meaning: '（会議を）休会にする', example: 'The meeting was adjourned until 3 p.m.', exampleJa: '会議は午後3時まで休会となった。', level: 860, category: '会議・プレゼン' },
  { id: 27, word: 'consensus', phonetic: '/kənˈsensəs/', pos: 'n.', meaning: '合意、総意', example: 'The team reached a consensus on the budget.', exampleJa: 'チームは予算について合意に達した。', level: 860, category: '会議・プレゼン' },
  { id: 28, word: 'summarize', phonetic: '/ˈsʌməraɪz/', pos: 'v.', meaning: '要約する', example: 'Could you summarize the report in one page?', exampleJa: 'その報告書を1ページに要約してもらえますか。', level: 730, category: '会議・プレゼン' },
  { id: 29, word: 'venue', phonetic: '/ˈvenjuː/', pos: 'n.', meaning: '会場、開催地', example: 'The venue has been changed to Hall B.', exampleJa: '会場はホールBに変更されました。', level: 730, category: '会議・プレゼン' },
  { id: 30, word: 'attendance', phonetic: '/əˈtendəns/', pos: 'n.', meaning: '出席、出席者数', example: 'Attendance at the seminar was low.', exampleJa: 'そのセミナーの出席者数は少なかった。', level: 730, category: '会議・プレゼン' },

  // ===== オフィス業務 =====
  { id: 31, word: 'deadline', phonetic: '/ˈdedlaɪn/', pos: 'n.', meaning: '締め切り', example: 'We must meet the deadline for the proposal.', exampleJa: '提案書の締め切りを守らなければならない。', level: 600, category: 'オフィス業務' },
  { id: 32, word: 'schedule', phonetic: '/ˈʃedjuːl/', pos: 'n./v.', meaning: '予定／予定を組む', example: 'The flight is scheduled to depart at noon.', exampleJa: 'その便は正午に出発予定だ。', level: 600, category: 'オフィス業務' },
  { id: 33, word: 'department', phonetic: '/dɪˈpɑːtmənt/', pos: 'n.', meaning: '部門、部署', example: 'She transferred to the sales department.', exampleJa: '彼女は営業部に異動した。', level: 600, category: 'オフィス業務' },
  { id: 34, word: 'colleague', phonetic: '/ˈkɒliːɡ/', pos: 'n.', meaning: '同僚', example: 'I discussed the plan with my colleagues.', exampleJa: '私はその計画を同僚たちと話し合った。', level: 600, category: 'オフィス業務' },
  { id: 35, word: 'assignment', phonetic: '/əˈsaɪnmənt/', pos: 'n.', meaning: '任務、割り当て', example: 'He completed the assignment ahead of time.', exampleJa: '彼は予定より早く任務を終えた。', level: 600, category: 'オフィス業務' },
  { id: 36, word: 'submit', phonetic: '/səbˈmɪt/', pos: 'v.', meaning: '提出する', example: 'Please submit the form by the end of the day.', exampleJa: '本日中にその用紙を提出してください。', level: 600, category: 'オフィス業務' },
  { id: 37, word: 'notify', phonetic: '/ˈnəʊtɪfaɪ/', pos: 'v.', meaning: '通知する', example: 'We will notify you once the item ships.', exampleJa: '商品が発送され次第ご連絡します。', level: 600, category: 'オフィス業務' },
  { id: 38, word: 'confirm', phonetic: '/kənˈfɜːm/', pos: 'v.', meaning: '確認する', example: 'Please confirm your reservation by email.', exampleJa: 'メールで予約を確認してください。', level: 600, category: 'オフィス業務' },
  { id: 39, word: 'reminder', phonetic: '/rɪˈmaɪndə/', pos: 'n.', meaning: 'リマインダー、注意喚起', example: 'This is a reminder that the office closes early today.', exampleJa: '本日は事務所が早く閉まることをお知らせします。', level: 730, category: 'オフィス業務' },
  { id: 40, word: 'delegate', phonetic: '/ˈdelɪɡeɪt/', pos: 'v.', meaning: '委任する', example: 'Good managers delegate tasks effectively.', exampleJa: '優れた管理職は仕事をうまく委任する。', level: 860, category: 'オフィス業務' },
  { id: 41, word: 'prioritize', phonetic: '/praɪˈɒrətaɪz/', pos: 'v.', meaning: '優先順位をつける', example: 'We need to prioritize customer requests.', exampleJa: '顧客の要望に優先順位をつける必要がある。', level: 730, category: 'オフィス業務' },
  { id: 42, word: 'streamline', phonetic: '/ˈstriːmlaɪn/', pos: 'v.', meaning: '効率化する、合理化する', example: 'The new system will streamline the approval process.', exampleJa: '新システムは承認手続きを効率化するだろう。', level: 860, category: 'オフィス業務' },
  { id: 43, word: 'attach', phonetic: '/əˈtætʃ/', pos: 'v.', meaning: '添付する', example: 'I have attached the revised document.', exampleJa: '修正した書類を添付しました。', level: 600, category: 'オフィス業務' },
  { id: 44, word: 'revise', phonetic: '/rɪˈvaɪz/', pos: 'v.', meaning: '修正する、改訂する', example: 'The manual was revised last year.', exampleJa: 'そのマニュアルは昨年改訂された。', level: 600, category: 'オフィス業務' },
  { id: 45, word: 'temporarily', phonetic: '/ˈtemprərəli/', pos: 'adv.', meaning: '一時的に', example: 'The elevator is temporarily out of service.', exampleJa: 'エレベーターは一時的に使用できません。', level: 730, category: 'オフィス業務' },
  { id: 46, word: 'accordingly', phonetic: '/əˈkɔːdɪŋli/', pos: 'adv.', meaning: 'それに応じて、したがって', example: 'Prices have risen, and we adjusted our budget accordingly.', exampleJa: '価格が上がったので、それに応じて予算を調整した。', level: 860, category: 'オフィス業務' },
  { id: 47, word: 'oversee', phonetic: '/ˌəʊvəˈsiː/', pos: 'v.', meaning: '監督する、統括する', example: 'She oversees three regional offices.', exampleJa: '彼女は3つの地域事務所を統括している。', level: 860, category: 'オフィス業務' },
  { id: 48, word: 'proceed', phonetic: '/prəˈsiːd/', pos: 'v.', meaning: '進む、続行する', example: 'Please proceed to gate 12 for boarding.', exampleJa: '搭乗のため12番ゲートへお進みください。', level: 730, category: 'オフィス業務' },
  { id: 49, word: 'implement', phonetic: '/ˈɪmplɪment/', pos: 'v.', meaning: '実施する、導入する', example: 'The policy will be implemented next quarter.', exampleJa: 'その方針は次の四半期に実施される。', level: 730, category: 'オフィス業務' },
  { id: 50, word: 'coordinate', phonetic: '/kəʊˈɔːdɪneɪt/', pos: 'v.', meaning: '調整する', example: 'She coordinates events for the marketing team.', exampleJa: '彼女はマーケティングチームのイベントを調整している。', level: 730, category: 'オフィス業務' },

  // ===== 財務・会計 =====
  { id: 51, word: 'invoice', phonetic: '/ˈɪnvɔɪs/', pos: 'n.', meaning: '請求書', example: 'The invoice must be paid within 30 days.', exampleJa: '請求書は30日以内に支払われなければならない。', level: 600, category: '財務・会計' },
  { id: 52, word: 'expense', phonetic: '/ɪkˈspens/', pos: 'n.', meaning: '経費、費用', example: 'Travel expenses will be reimbursed.', exampleJa: '出張費は払い戻されます。', level: 600, category: '財務・会計' },
  { id: 53, word: 'budget', phonetic: '/ˈbʌdʒɪt/', pos: 'n.', meaning: '予算', example: 'The project went over budget.', exampleJa: 'そのプロジェクトは予算を超過した。', level: 600, category: '財務・会計' },
  { id: 54, word: 'revenue', phonetic: '/ˈrevənjuː/', pos: 'n.', meaning: '収益、歳入', example: 'Annual revenue increased by 12 percent.', exampleJa: '年間収益は12％増加した。', level: 730, category: '財務・会計' },
  { id: 55, word: 'reimburse', phonetic: '/ˌriːɪmˈbɜːs/', pos: 'v.', meaning: '払い戻す、精算する', example: 'The company will reimburse you for the taxi fare.', exampleJa: '会社がタクシー代を払い戻します。', level: 730, category: '財務・会計' },
  { id: 56, word: 'receipt', phonetic: '/rɪˈsiːt/', pos: 'n.', meaning: '領収書、受領', example: 'Keep your receipt for a refund.', exampleJa: '返金のため領収書を保管してください。', level: 600, category: '財務・会計' },
  { id: 57, word: 'refund', phonetic: '/ˈriːfʌnd/', pos: 'n./v.', meaning: '返金／返金する', example: 'We offer a full refund within 14 days.', exampleJa: '14日以内であれば全額返金いたします。', level: 600, category: '財務・会計' },
  { id: 58, word: 'accounting', phonetic: '/əˈkaʊntɪŋ/', pos: 'n.', meaning: '会計、経理', example: 'Send the form to the accounting department.', exampleJa: 'その用紙を経理部に送ってください。', level: 600, category: '財務・会計' },
  { id: 59, word: 'audit', phonetic: '/ˈɔːdɪt/', pos: 'n./v.', meaning: '監査／監査する', example: 'An outside firm will audit our accounts.', exampleJa: '外部の会社が当社の会計を監査する。', level: 860, category: '財務・会計' },
  { id: 60, word: 'profit', phonetic: '/ˈprɒfɪt/', pos: 'n.', meaning: '利益', example: 'The store made a small profit last year.', exampleJa: 'その店は昨年わずかな利益を上げた。', level: 600, category: '財務・会計' },
  { id: 61, word: 'deposit', phonetic: '/dɪˈpɒzɪt/', pos: 'n./v.', meaning: '手付金、預金／預ける', example: 'A deposit of 20 percent is required.', exampleJa: '20％の手付金が必要です。', level: 730, category: '財務・会計' },
  { id: 62, word: 'fiscal', phonetic: '/ˈfɪskl/', pos: 'adj.', meaning: '財政の、会計の', example: 'Our fiscal year ends in March.', exampleJa: '当社の会計年度は3月に終わる。', level: 860, category: '財務・会計' },
  { id: 63, word: 'installment', phonetic: '/ɪnˈstɔːlmənt/', pos: 'n.', meaning: '分割払い、一回分', example: 'You can pay in twelve monthly installments.', exampleJa: '12回の月賦でお支払いいただけます。', level: 860, category: '財務・会計' },
  { id: 64, word: 'estimate', phonetic: '/ˈestɪmət/', pos: 'n./v.', meaning: '見積もり／見積もる', example: 'Could you send us a cost estimate?', exampleJa: '費用の見積もりを送っていただけますか。', level: 600, category: '財務・会計' },
  { id: 65, word: 'due', phonetic: '/djuː/', pos: 'adj.', meaning: '期限が来た、支払うべき', example: 'The payment is due on the first of the month.', exampleJa: '支払いは月の初日が期限です。', level: 600, category: '財務・会計' },

  // ===== 契約・法務 =====
  { id: 66, word: 'contract', phonetic: '/ˈkɒntrækt/', pos: 'n.', meaning: '契約、契約書', example: 'Both parties signed the contract yesterday.', exampleJa: '両者は昨日その契約書に署名した。', level: 600, category: '契約・法務' },
  { id: 67, word: 'agreement', phonetic: '/əˈɡriːmənt/', pos: 'n.', meaning: '合意、協定', example: 'We reached an agreement after long talks.', exampleJa: '長い協議の末、我々は合意に達した。', level: 600, category: '契約・法務' },
  { id: 68, word: 'terms', phonetic: '/tɜːmz/', pos: 'n.', meaning: '条件、契約条項', example: 'Please read the terms carefully before signing.', exampleJa: '署名前に条件をよくお読みください。', level: 730, category: '契約・法務' },
  { id: 69, word: 'negotiate', phonetic: '/nɪˈɡəʊʃieɪt/', pos: 'v.', meaning: '交渉する', example: 'They negotiated a better price.', exampleJa: '彼らはより良い価格を交渉した。', level: 730, category: '契約・法務' },
  { id: 70, word: 'renew', phonetic: '/rɪˈnjuː/', pos: 'v.', meaning: '更新する', example: 'You must renew your membership annually.', exampleJa: '会員資格は毎年更新しなければならない。', level: 600, category: '契約・法務' },
  { id: 71, word: 'comply', phonetic: '/kəmˈplaɪ/', pos: 'v.', meaning: '（規則に）従う', example: 'All staff must comply with safety regulations.', exampleJa: '全職員は安全規則に従わなければならない。', level: 730, category: '契約・法務' },
  { id: 72, word: 'regulation', phonetic: '/ˌreɡjuˈleɪʃn/', pos: 'n.', meaning: '規則、規制', example: 'New environmental regulations take effect in July.', exampleJa: '新しい環境規制は7月に発効する。', level: 730, category: '契約・法務' },
  { id: 73, word: 'liability', phonetic: '/ˌlaɪəˈbɪləti/', pos: 'n.', meaning: '責任、負債', example: 'The clause limits the company’s liability.', exampleJa: 'その条項は会社の責任を制限している。', level: 860, category: '契約・法務' },
  { id: 74, word: 'expire', phonetic: '/ɪkˈspaɪə/', pos: 'v.', meaning: '期限が切れる', example: 'The warranty expires next month.', exampleJa: '保証は来月切れる。', level: 730, category: '契約・法務' },
  { id: 75, word: 'binding', phonetic: '/ˈbaɪndɪŋ/', pos: 'adj.', meaning: '拘束力のある', example: 'The agreement is legally binding.', exampleJa: 'その合意は法的拘束力がある。', level: 860, category: '契約・法務' },
  { id: 76, word: 'waive', phonetic: '/weɪv/', pos: 'v.', meaning: '（権利などを）放棄する、免除する', example: 'The bank waived the transfer fee.', exampleJa: '銀行は振込手数料を免除した。', level: 860, category: '契約・法務' },
  { id: 77, word: 'clause', phonetic: '/klɔːz/', pos: 'n.', meaning: '条項', example: 'Refer to clause 5 of the contract.', exampleJa: '契約書の第5条を参照してください。', level: 860, category: '契約・法務' },
  { id: 78, word: 'obligation', phonetic: '/ˌɒblɪˈɡeɪʃn/', pos: 'n.', meaning: '義務', example: 'You are under no obligation to buy.', exampleJa: '購入の義務は一切ありません。', level: 860, category: '契約・法務' },
  { id: 79, word: 'authorize', phonetic: '/ˈɔːθəraɪz/', pos: 'v.', meaning: '許可する、権限を与える', example: 'Only managers can authorize refunds.', exampleJa: '返金を承認できるのは管理職だけだ。', level: 730, category: '契約・法務' },
  { id: 80, word: 'valid', phonetic: '/ˈvælɪd/', pos: 'adj.', meaning: '有効な', example: 'This coupon is valid until December 31.', exampleJa: 'このクーポンは12月31日まで有効です。', level: 600, category: '契約・法務' },

  // ===== マーケティング・営業 =====
  { id: 81, word: 'client', phonetic: '/ˈklaɪənt/', pos: 'n.', meaning: '顧客、依頼人', example: 'Our largest client is based in Singapore.', exampleJa: '当社の最大の顧客はシンガポールにある。', level: 600, category: 'マーケ・営業' },
  { id: 82, word: 'merchandise', phonetic: '/ˈmɜːtʃəndaɪs/', pos: 'n.', meaning: '商品', example: 'All merchandise is 30 percent off today.', exampleJa: '本日は全商品30％引きです。', level: 730, category: 'マーケ・営業' },
  { id: 83, word: 'discount', phonetic: '/ˈdɪskaʊnt/', pos: 'n.', meaning: '割引', example: 'Members receive a 10 percent discount.', exampleJa: '会員は10％の割引を受けられます。', level: 600, category: 'マーケ・営業' },
  { id: 84, word: 'advertisement', phonetic: '/ədˈvɜːtɪsmənt/', pos: 'n.', meaning: '広告', example: 'The advertisement will run in three magazines.', exampleJa: 'その広告は3誌に掲載される。', level: 600, category: 'マーケ・営業' },
  { id: 85, word: 'launch', phonetic: '/lɔːntʃ/', pos: 'v./n.', meaning: '発売する、開始する／発売', example: 'They will launch the new model in spring.', exampleJa: '彼らは春に新型を発売する。', level: 600, category: 'マーケ・営業' },
  { id: 86, word: 'competitor', phonetic: '/kəmˈpetɪtə/', pos: 'n.', meaning: '競合他社', example: 'Our competitors lowered their prices.', exampleJa: '競合他社は価格を下げた。', level: 600, category: 'マーケ・営業' },
  { id: 87, word: 'survey', phonetic: '/ˈsɜːveɪ/', pos: 'n.', meaning: '調査、アンケート', example: 'The survey showed high customer satisfaction.', exampleJa: '調査は高い顧客満足度を示した。', level: 600, category: 'マーケ・営業' },
  { id: 88, word: 'demand', phonetic: '/dɪˈmɑːnd/', pos: 'n.', meaning: '需要', example: 'Demand for electric cars is rising.', exampleJa: '電気自動車の需要が高まっている。', level: 600, category: 'マーケ・営業' },
  { id: 89, word: 'promotional', phonetic: '/prəˈməʊʃənl/', pos: 'adj.', meaning: '販売促進の', example: 'We handed out promotional items at the fair.', exampleJa: '展示会で販促品を配布した。', level: 730, category: 'マーケ・営業' },
  { id: 90, word: 'retail', phonetic: '/ˈriːteɪl/', pos: 'n./adj.', meaning: '小売／小売の', example: 'The retail price is higher than expected.', exampleJa: '小売価格は予想より高い。', level: 730, category: 'マーケ・営業' },
  { id: 91, word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', pos: 'v.', meaning: '予期する、見込む', example: 'We anticipate strong sales this quarter.', exampleJa: '今四半期は好調な売上を見込んでいる。', level: 860, category: 'マーケ・営業' },
  { id: 92, word: 'substantial', phonetic: '/səbˈstænʃl/', pos: 'adj.', meaning: 'かなりの、相当な', example: 'The campaign brought a substantial increase in sales.', exampleJa: 'そのキャンペーンは売上の大幅な増加をもたらした。', level: 860, category: 'マーケ・営業' },
  { id: 93, word: 'testimonial', phonetic: '/ˌtestɪˈməʊniəl/', pos: 'n.', meaning: '推薦の言葉、体験談', example: 'Customer testimonials appear on our website.', exampleJa: '顧客の体験談が当社サイトに掲載されている。', level: 860, category: 'マーケ・営業' },
  { id: 94, word: 'subscription', phonetic: '/səbˈskrɪpʃn/', pos: 'n.', meaning: '定期購読、契約', example: 'Your subscription renews automatically.', exampleJa: 'ご契約は自動で更新されます。', level: 730, category: 'マーケ・営業' },
  { id: 95, word: 'complimentary', phonetic: '/ˌkɒmplɪˈmentri/', pos: 'adj.', meaning: '無料の', example: 'Guests receive a complimentary breakfast.', exampleJa: '宿泊客は無料の朝食を受けられます。', level: 860, category: 'マーケ・営業' },

  // ===== 物流・発注 =====
  { id: 96, word: 'shipment', phonetic: '/ˈʃɪpmənt/', pos: 'n.', meaning: '発送、積荷', example: 'The shipment will arrive on Tuesday.', exampleJa: '荷物は火曜日に到着します。', level: 600, category: '物流・発注' },
  { id: 97, word: 'deliver', phonetic: '/dɪˈlɪvə/', pos: 'v.', meaning: '配達する', example: 'We deliver orders within two business days.', exampleJa: '注文品は2営業日以内に配達します。', level: 600, category: '物流・発注' },
  { id: 98, word: 'inventory', phonetic: '/ˈɪnvəntri/', pos: 'n.', meaning: '在庫、棚卸し', example: 'We take inventory at the end of each month.', exampleJa: '毎月末に棚卸しを行う。', level: 730, category: '物流・発注' },
  { id: 99, word: 'warehouse', phonetic: '/ˈweəhaʊs/', pos: 'n.', meaning: '倉庫', example: 'The goods are stored in a nearby warehouse.', exampleJa: '商品は近くの倉庫に保管されている。', level: 600, category: '物流・発注' },
  { id: 100, word: 'supplier', phonetic: '/səˈplaɪə/', pos: 'n.', meaning: '供給業者、仕入先', example: 'We switched to a cheaper supplier.', exampleJa: 'より安い仕入先に切り替えた。', level: 600, category: '物流・発注' },
  { id: 101, word: 'defective', phonetic: '/dɪˈfektɪv/', pos: 'adj.', meaning: '欠陥のある', example: 'Return any defective items for replacement.', exampleJa: '欠陥品はお取り替えのためご返送ください。', level: 730, category: '物流・発注' },
  { id: 102, word: 'warranty', phonetic: '/ˈwɒrənti/', pos: 'n.', meaning: '保証（書）', example: 'The laptop comes with a two-year warranty.', exampleJa: 'そのノートPCには2年保証が付いている。', level: 730, category: '物流・発注' },
  { id: 103, word: 'freight', phonetic: '/freɪt/', pos: 'n.', meaning: '貨物、運送料', example: 'Freight charges are not included in the price.', exampleJa: '運送料は価格に含まれていません。', level: 860, category: '物流・発注' },
  { id: 104, word: 'backorder', phonetic: '/ˈbækɔːdə/', pos: 'n.', meaning: '入荷待ちの注文', example: 'The item is on backorder until next month.', exampleJa: 'その商品は来月まで入荷待ちです。', level: 860, category: '物流・発注' },
  { id: 105, word: 'distribute', phonetic: '/dɪˈstrɪbjuːt/', pos: 'v.', meaning: '配布する、流通させる', example: 'The company distributes products across Asia.', exampleJa: 'その会社はアジア全域に製品を流通させている。', level: 730, category: '物流・発注' },
  { id: 106, word: 'purchase', phonetic: '/ˈpɜːtʃəs/', pos: 'v./n.', meaning: '購入する／購入', example: 'Please keep proof of purchase.', exampleJa: '購入証明を保管してください。', level: 600, category: '物流・発注' },
  { id: 107, word: 'in stock', phonetic: '/ɪn stɒk/', pos: 'phr.', meaning: '在庫がある', example: 'The blue model is no longer in stock.', exampleJa: '青いモデルはもう在庫がありません。', level: 600, category: '物流・発注' },
  { id: 108, word: 'delay', phonetic: '/dɪˈleɪ/', pos: 'n./v.', meaning: '遅延／遅らせる', example: 'Bad weather caused a two-hour delay.', exampleJa: '悪天候により2時間の遅延が生じた。', level: 600, category: '物流・発注' },
  { id: 109, word: 'consignment', phonetic: '/kənˈsaɪnmənt/', pos: 'n.', meaning: '委託販売、積荷', example: 'The consignment arrived at the port today.', exampleJa: '積荷は本日港に到着した。', level: 860, category: '物流・発注' },
  { id: 110, word: 'expedite', phonetic: '/ˈekspədaɪt/', pos: 'v.', meaning: '迅速に処理する', example: 'We can expedite your order for a small fee.', exampleJa: '少額の手数料でご注文を迅速に処理できます。', level: 860, category: '物流・発注' },

  // ===== 出張・旅行 =====
  { id: 111, word: 'itinerary', phonetic: '/aɪˈtɪnərəri/', pos: 'n.', meaning: '旅程表', example: 'I emailed you the itinerary for the trip.', exampleJa: '出張の旅程表をメールで送りました。', level: 730, category: '出張・旅行' },
  { id: 112, word: 'reservation', phonetic: '/ˌrezəˈveɪʃn/', pos: 'n.', meaning: '予約', example: 'I made a reservation for two nights.', exampleJa: '2泊の予約をしました。', level: 600, category: '出張・旅行' },
  { id: 113, word: 'boarding', phonetic: '/ˈbɔːdɪŋ/', pos: 'n.', meaning: '搭乗', example: 'Boarding begins thirty minutes before departure.', exampleJa: '搭乗は出発の30分前に始まります。', level: 600, category: '出張・旅行' },
  { id: 114, word: 'luggage', phonetic: '/ˈlʌɡɪdʒ/', pos: 'n.', meaning: '手荷物', example: 'You may carry one piece of luggage.', exampleJa: '手荷物は1つまでお持ちいただけます。', level: 600, category: '出張・旅行' },
  { id: 115, word: 'departure', phonetic: '/dɪˈpɑːtʃə/', pos: 'n.', meaning: '出発', example: 'Check the departure time on your ticket.', exampleJa: 'チケットで出発時刻を確認してください。', level: 600, category: '出張・旅行' },
  { id: 116, word: 'accommodation', phonetic: '/əˌkɒməˈdeɪʃn/', pos: 'n.', meaning: '宿泊施設', example: 'Accommodation will be arranged by the company.', exampleJa: '宿泊は会社が手配します。', level: 730, category: '出張・旅行' },
  { id: 117, word: 'detour', phonetic: '/ˈdiːtʊə/', pos: 'n.', meaning: '迂回路', example: 'Drivers must take a detour due to construction.', exampleJa: '工事のため運転者は迂回路を使わなければならない。', level: 730, category: '出張・旅行' },
  { id: 118, word: 'fare', phonetic: '/feə/', pos: 'n.', meaning: '運賃', example: 'The bus fare has gone up again.', exampleJa: 'バス運賃がまた上がった。', level: 600, category: '出張・旅行' },
  { id: 119, word: 'shuttle', phonetic: '/ˈʃʌtl/', pos: 'n.', meaning: '送迎バス', example: 'A free shuttle runs to the airport.', exampleJa: '空港行きの無料送迎バスが運行しています。', level: 730, category: '出張・旅行' },
  { id: 120, word: 'destination', phonetic: '/ˌdestɪˈneɪʃn/', pos: 'n.', meaning: '目的地', example: 'Our final destination is Osaka.', exampleJa: '最終目的地は大阪です。', level: 600, category: '出張・旅行' },
  { id: 121, word: 'layover', phonetic: '/ˈleɪəʊvə/', pos: 'n.', meaning: '（飛行機の）乗り継ぎ待ち', example: 'We have a three-hour layover in Seoul.', exampleJa: 'ソウルで3時間の乗り継ぎ待ちがある。', level: 860, category: '出張・旅行' },
  { id: 122, word: 'vacancy', phonetic: '/ˈveɪkənsi/', pos: 'n.', meaning: '空室、欠員', example: 'The hotel has no vacancies this weekend.', exampleJa: 'そのホテルは今週末空室がない。', level: 730, category: '出張・旅行' },
  { id: 123, word: 'confirmation', phonetic: '/ˌkɒnfəˈmeɪʃn/', pos: 'n.', meaning: '確認、確認書', example: 'Show your confirmation number at the desk.', exampleJa: '受付で確認番号をご提示ください。', level: 600, category: '出張・旅行' },
  { id: 124, word: 'excursion', phonetic: '/ɪkˈskɜːʃn/', pos: 'n.', meaning: '小旅行、遠足', example: 'A guided excursion is included in the tour.', exampleJa: 'ガイド付きの小旅行がツアーに含まれています。', level: 860, category: '出張・旅行' },
  { id: 125, word: 'in advance', phonetic: '/ɪn ədˈvɑːns/', pos: 'phr.', meaning: '事前に', example: 'Tickets must be booked in advance.', exampleJa: 'チケットは事前に予約が必要です。', level: 600, category: '出張・旅行' },

  // ===== 施設・設備 =====
  { id: 126, word: 'facility', phonetic: '/fəˈsɪləti/', pos: 'n.', meaning: '施設、設備', example: 'The new facility opens in June.', exampleJa: '新しい施設は6月に開業する。', level: 600, category: '施設・設備' },
  { id: 127, word: 'maintenance', phonetic: '/ˈmeɪntənəns/', pos: 'n.', meaning: '保守、整備', example: 'The pool is closed for maintenance.', exampleJa: 'プールは整備のため閉鎖中です。', level: 600, category: '施設・設備' },
  { id: 128, word: 'renovation', phonetic: '/ˌrenəˈveɪʃn/', pos: 'n.', meaning: '改装、改修', example: 'The lobby is under renovation.', exampleJa: 'ロビーは改装中です。', level: 730, category: '施設・設備' },
  { id: 129, word: 'premises', phonetic: '/ˈpremɪsɪz/', pos: 'n.', meaning: '敷地、建物内', example: 'Smoking is prohibited on the premises.', exampleJa: '敷地内は禁煙です。', level: 860, category: '施設・設備' },
  { id: 130, word: 'inspection', phonetic: '/ɪnˈspekʃn/', pos: 'n.', meaning: '検査、点検', example: 'A safety inspection is held every year.', exampleJa: '安全点検は毎年行われる。', level: 730, category: '施設・設備' },
  { id: 131, word: 'install', phonetic: '/ɪnˈstɔːl/', pos: 'v.', meaning: '設置する、導入する', example: 'New lights were installed in the parking lot.', exampleJa: '駐車場に新しい照明が設置された。', level: 600, category: '施設・設備' },
  { id: 132, word: 'occupy', phonetic: '/ˈɒkjupaɪ/', pos: 'v.', meaning: '占める、使用中である', example: 'The meeting room is occupied until noon.', exampleJa: '会議室は正午まで使用中です。', level: 730, category: '施設・設備' },
  { id: 133, word: 'relocate', phonetic: '/ˌriːləʊˈkeɪt/', pos: 'v.', meaning: '移転する', example: 'The head office relocated to Chicago.', exampleJa: '本社はシカゴに移転した。', level: 730, category: '施設・設備' },
  { id: 134, word: 'temporary', phonetic: '/ˈtemprəri/', pos: 'adj.', meaning: '一時的な', example: 'A temporary entrance is on the north side.', exampleJa: '仮設の入口は北側にあります。', level: 600, category: '施設・設備' },
  { id: 135, word: 'accessible', phonetic: '/əkˈsesəbl/', pos: 'adj.', meaning: '利用しやすい、行きやすい', example: 'The building is accessible by wheelchair.', exampleJa: 'その建物は車椅子で利用できる。', level: 730, category: '施設・設備' },

  // ===== 製造・技術 =====
  { id: 136, word: 'manufacture', phonetic: '/ˌmænjuˈfæktʃə/', pos: 'v.', meaning: '製造する', example: 'The parts are manufactured in Vietnam.', exampleJa: 'その部品はベトナムで製造されている。', level: 600, category: '製造・技術' },
  { id: 137, word: 'assemble', phonetic: '/əˈsembl/', pos: 'v.', meaning: '組み立てる、集まる', example: 'Workers assemble the units by hand.', exampleJa: '作業員が手作業でその装置を組み立てる。', level: 730, category: '製造・技術' },
  { id: 138, word: 'durable', phonetic: '/ˈdjʊərəbl/', pos: 'adj.', meaning: '耐久性のある', example: 'This fabric is light but durable.', exampleJa: 'この生地は軽いが耐久性がある。', level: 730, category: '製造・技術' },
  { id: 139, word: 'malfunction', phonetic: '/ˌmælˈfʌŋkʃn/', pos: 'n./v.', meaning: '故障／故障する', example: 'The printer has been malfunctioning all week.', exampleJa: 'プリンターは今週ずっと故障している。', level: 860, category: '製造・技術' },
  { id: 140, word: 'specification', phonetic: '/ˌspesɪfɪˈkeɪʃn/', pos: 'n.', meaning: '仕様（書）', example: 'The product meets all specifications.', exampleJa: 'その製品は全ての仕様を満たしている。', level: 730, category: '製造・技術' },
  { id: 141, word: 'upgrade', phonetic: '/ˈʌpɡreɪd/', pos: 'v./n.', meaning: 'アップグレードする／改良', example: 'We upgraded the software last night.', exampleJa: '昨夜ソフトウェアを更新した。', level: 600, category: '製造・技術' },
  { id: 142, word: 'efficiency', phonetic: '/ɪˈfɪʃnsi/', pos: 'n.', meaning: '効率', example: 'The new line improved efficiency by 20 percent.', exampleJa: '新ラインは効率を20％向上させた。', level: 730, category: '製造・技術' },
  { id: 143, word: 'prototype', phonetic: '/ˈprəʊtətaɪp/', pos: 'n.', meaning: '試作品', example: 'The prototype will be tested next week.', exampleJa: '試作品は来週テストされる。', level: 860, category: '製造・技術' },
  { id: 144, word: 'component', phonetic: '/kəmˈpəʊnənt/', pos: 'n.', meaning: '部品、構成要素', example: 'A key component was missing from the box.', exampleJa: '重要な部品が箱に入っていなかった。', level: 860, category: '製造・技術' },
  { id: 145, word: 'capacity', phonetic: '/kəˈpæsəti/', pos: 'n.', meaning: '容量、収容力', example: 'The plant is operating at full capacity.', exampleJa: '工場はフル稼働している。', level: 730, category: '製造・技術' },

  // ===== 顧客対応 =====
  { id: 146, word: 'complaint', phonetic: '/kəmˈpleɪnt/', pos: 'n.', meaning: '苦情', example: 'We received several complaints about the noise.', exampleJa: '騒音について複数の苦情を受けた。', level: 600, category: '顧客対応' },
  { id: 147, word: 'inquiry', phonetic: '/ɪnˈkwaɪəri/', pos: 'n.', meaning: '問い合わせ', example: 'Please direct your inquiry to our support team.', exampleJa: 'お問い合わせはサポート部門までお願いします。', level: 600, category: '顧客対応' },
  { id: 148, word: 'apologize', phonetic: '/əˈpɒlədʒaɪz/', pos: 'v.', meaning: '謝罪する', example: 'We apologize for the inconvenience.', exampleJa: 'ご不便をおかけし申し訳ありません。', level: 600, category: '顧客対応' },
  { id: 149, word: 'inconvenience', phonetic: '/ˌɪnkənˈviːniəns/', pos: 'n.', meaning: '不便、迷惑', example: 'We regret any inconvenience caused by the delay.', exampleJa: '遅延によるご不便をお詫びします。', level: 730, category: '顧客対応' },
  { id: 150, word: 'satisfaction', phonetic: '/ˌsætɪsˈfækʃn/', pos: 'n.', meaning: '満足', example: 'Customer satisfaction is our top priority.', exampleJa: '顧客満足が私たちの最優先事項です。', level: 600, category: '顧客対応' },
  { id: 151, word: 'replacement', phonetic: '/rɪˈpleɪsmənt/', pos: 'n.', meaning: '交換品、後任', example: 'A replacement will be sent free of charge.', exampleJa: '交換品を無料でお送りします。', level: 730, category: '顧客対応' },
  { id: 152, word: 'courteous', phonetic: '/ˈkɜːtiəs/', pos: 'adj.', meaning: '礼儀正しい', example: 'The staff were courteous and helpful.', exampleJa: 'スタッフは礼儀正しく親切だった。', level: 860, category: '顧客対応' },
  { id: 153, word: 'promptly', phonetic: '/ˈprɒmptli/', pos: 'adv.', meaning: '迅速に、時間通りに', example: 'Your request will be handled promptly.', exampleJa: 'ご依頼は迅速に対応いたします。', level: 730, category: '顧客対応' },
  { id: 154, word: 'feedback', phonetic: '/ˈfiːdbæk/', pos: 'n.', meaning: '意見、感想', example: 'We value your feedback on our service.', exampleJa: 'サービスへのご意見を大切にしています。', level: 600, category: '顧客対応' },
  { id: 155, word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', pos: 'v.', meaning: '（要望に）応じる、収容する', example: 'The hall can accommodate 500 guests.', exampleJa: 'そのホールは500人を収容できる。', level: 860, category: '顧客対応' },

  // ===== 一般ビジネス =====
  { id: 156, word: 'available', phonetic: '/əˈveɪləbl/', pos: 'adj.', meaning: '利用できる、手が空いている', example: 'Dr. Lee is not available this afternoon.', exampleJa: 'リー先生は今日の午後は手が空いていません。', level: 600, category: '一般ビジネス' },
  { id: 157, word: 'require', phonetic: '/rɪˈkwaɪə/', pos: 'v.', meaning: '必要とする、要求する', example: 'This position requires three years of experience.', exampleJa: 'この職は3年の経験を必要とする。', level: 600, category: '一般ビジネス' },
  { id: 158, word: 'ensure', phonetic: '/ɪnˈʃʊə/', pos: 'v.', meaning: '確実にする、保証する', example: 'Please ensure that all doors are locked.', exampleJa: '全てのドアが施錠されていることを確認してください。', level: 730, category: '一般ビジネス' },
  { id: 159, word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', pos: 'adj.', meaning: '重要な、著しい', example: 'There was a significant drop in attendance.', exampleJa: '出席者数が著しく減少した。', level: 730, category: '一般ビジネス' },
  { id: 160, word: 'approximately', phonetic: '/əˈprɒksɪmətli/', pos: 'adv.', meaning: 'おおよそ', example: 'The trip takes approximately two hours.', exampleJa: 'その移動には約2時間かかる。', level: 600, category: '一般ビジネス' },
  { id: 161, word: 'previous', phonetic: '/ˈpriːviəs/', pos: 'adj.', meaning: '以前の', example: 'Refer to the previous version of the file.', exampleJa: 'そのファイルの以前の版を参照してください。', level: 600, category: '一般ビジネス' },
  { id: 162, word: 'currently', phonetic: '/ˈkʌrəntli/', pos: 'adv.', meaning: '現在は', example: 'The website is currently under construction.', exampleJa: 'そのサイトは現在構築中です。', level: 600, category: '一般ビジネス' },
  { id: 163, word: 'regarding', phonetic: '/rɪˈɡɑːdɪŋ/', pos: 'prep.', meaning: '〜に関して', example: 'I am writing regarding your recent order.', exampleJa: '先日のご注文についてご連絡しております。', level: 730, category: '一般ビジネス' },
  { id: 164, word: 'furthermore', phonetic: '/ˌfɜːðəˈmɔː/', pos: 'adv.', meaning: 'さらに', example: 'Furthermore, the price includes installation.', exampleJa: 'さらに、価格には設置費用が含まれます。', level: 730, category: '一般ビジネス' },
  { id: 165, word: 'nevertheless', phonetic: '/ˌnevəðəˈles/', pos: 'adv.', meaning: 'それにもかかわらず', example: 'It rained; nevertheless, the event went ahead.', exampleJa: '雨が降ったが、それでもイベントは実施された。', level: 860, category: '一般ビジネス' },
  { id: 166, word: 'initiative', phonetic: '/ɪˈnɪʃətɪv/', pos: 'n.', meaning: '新たな取り組み、主導権', example: 'The company launched a green initiative.', exampleJa: 'その会社は環境への取り組みを開始した。', level: 860, category: '一般ビジネス' },
  { id: 167, word: 'feasible', phonetic: '/ˈfiːzəbl/', pos: 'adj.', meaning: '実行可能な', example: 'The plan is not feasible within our budget.', exampleJa: 'その計画は予算内では実行できない。', level: 860, category: '一般ビジネス' },
  { id: 168, word: 'thorough', phonetic: '/ˈθʌrə/', pos: 'adj.', meaning: '徹底的な', example: 'A thorough review of the data is needed.', exampleJa: 'データの徹底的な見直しが必要だ。', level: 860, category: '一般ビジネス' },
  { id: 169, word: 'diverse', phonetic: '/daɪˈvɜːs/', pos: 'adj.', meaning: '多様な', example: 'Our staff comes from diverse backgrounds.', exampleJa: '当社の社員は多様な背景を持つ。', level: 860, category: '一般ビジネス' },
  { id: 170, word: 'collaborate', phonetic: '/kəˈlæbəreɪt/', pos: 'v.', meaning: '協力する', example: 'The two firms collaborated on the design.', exampleJa: '両社は設計で協力した。', level: 730, category: '一般ビジネス' },
  { id: 171, word: 'objective', phonetic: '/əbˈdʒektɪv/', pos: 'n.', meaning: '目標、目的', example: 'Our main objective is to cut costs.', exampleJa: '私たちの主な目標はコスト削減だ。', level: 730, category: '一般ビジネス' },
  { id: 172, word: 'expand', phonetic: '/ɪkˈspænd/', pos: 'v.', meaning: '拡大する', example: 'The chain plans to expand into Europe.', exampleJa: 'そのチェーンは欧州への拡大を計画している。', level: 600, category: '一般ビジネス' },
  { id: 173, word: 'reduce', phonetic: '/rɪˈdjuːs/', pos: 'v.', meaning: '減らす', example: 'We reduced waste by half.', exampleJa: '廃棄物を半分に減らした。', level: 600, category: '一般ビジネス' },
  { id: 174, word: 'achieve', phonetic: '/əˈtʃiːv/', pos: 'v.', meaning: '達成する', example: 'The team achieved its sales target.', exampleJa: 'チームは売上目標を達成した。', level: 600, category: '一般ビジネス' },
  { id: 175, word: 'issue', phonetic: '/ˈɪʃuː/', pos: 'n./v.', meaning: '問題、発行物／発行する', example: 'The magazine issues a special edition yearly.', exampleJa: 'その雑誌は毎年特別号を発行する。', level: 600, category: '一般ビジネス' },

  // ===== 頻出フレーズ =====
  { id: 176, word: 'be responsible for', phonetic: '/bi rɪˈspɒnsəbl fɔː/', pos: 'phr.', meaning: '〜に責任がある、〜を担当する', example: 'She is responsible for training new hires.', exampleJa: '彼女は新入社員の研修を担当している。', level: 600, category: '頻出フレーズ' },
  { id: 177, word: 'take advantage of', phonetic: '/teɪk ədˈvɑːntɪdʒ ɒv/', pos: 'phr.', meaning: '〜を利用する', example: 'Take advantage of our summer sale.', exampleJa: '夏のセールをぜひご利用ください。', level: 730, category: '頻出フレーズ' },
  { id: 178, word: 'be subject to', phonetic: '/bi ˈsʌbdʒɪkt tuː/', pos: 'phr.', meaning: '〜の対象となる、〜次第である', example: 'Prices are subject to change without notice.', exampleJa: '価格は予告なく変更される場合があります。', level: 860, category: '頻出フレーズ' },
  { id: 179, word: 'look forward to', phonetic: '/lʊk ˈfɔːwəd tuː/', pos: 'phr.', meaning: '〜を楽しみに待つ', example: 'We look forward to hearing from you.', exampleJa: 'ご連絡をお待ちしております。', level: 600, category: '頻出フレーズ' },
  { id: 180, word: 'in charge of', phonetic: '/ɪn tʃɑːdʒ ɒv/', pos: 'phr.', meaning: '〜を担当して', example: 'Who is in charge of the project?', exampleJa: '誰がそのプロジェクトの担当ですか。', level: 600, category: '頻出フレーズ' },
  { id: 181, word: 'as of', phonetic: '/æz ɒv/', pos: 'phr.', meaning: '〜の時点で、〜付けで', example: 'As of April 1, the new rate applies.', exampleJa: '4月1日付けで新料金が適用されます。', level: 730, category: '頻出フレーズ' },
  { id: 182, word: 'on behalf of', phonetic: '/ɒn bɪˈhɑːf ɒv/', pos: 'phr.', meaning: '〜を代表して、〜の代わりに', example: 'On behalf of the staff, thank you.', exampleJa: 'スタッフを代表して、御礼申し上げます。', level: 860, category: '頻出フレーズ' },
  { id: 183, word: 'in accordance with', phonetic: '/ɪn əˈkɔːdns wɪð/', pos: 'phr.', meaning: '〜に従って', example: 'Work in accordance with the safety manual.', exampleJa: '安全マニュアルに従って作業してください。', level: 860, category: '頻出フレーズ' },
  { id: 184, word: 'be eligible for', phonetic: '/bi ˈelɪdʒəbl fɔː/', pos: 'phr.', meaning: '〜の資格がある', example: 'Employees are eligible for a bonus after one year.', exampleJa: '社員は1年後に賞与の資格を得る。', level: 730, category: '頻出フレーズ' },
  { id: 185, word: 'keep track of', phonetic: '/kiːp træk ɒv/', pos: 'phr.', meaning: '〜を把握しておく', example: 'Use this app to keep track of expenses.', exampleJa: '経費を把握するのにこのアプリを使ってください。', level: 730, category: '頻出フレーズ' },
  { id: 186, word: 'no later than', phonetic: '/nəʊ ˈleɪtə ðæn/', pos: 'phr.', meaning: '遅くとも〜までに', example: 'Reply no later than Friday.', exampleJa: '遅くとも金曜日までに返信してください。', level: 730, category: '頻出フレーズ' },
  { id: 187, word: 'free of charge', phonetic: '/friː ɒv tʃɑːdʒ/', pos: 'phr.', meaning: '無料で', example: 'Delivery is free of charge for members.', exampleJa: '会員は配送料無料です。', level: 600, category: '頻出フレーズ' },
  { id: 188, word: 'due to', phonetic: '/djuː tuː/', pos: 'phr.', meaning: '〜が原因で', example: 'The flight was canceled due to fog.', exampleJa: '霧のため便は欠航した。', level: 600, category: '頻出フレーズ' },
  { id: 189, word: 'rather than', phonetic: '/ˈrɑːðə ðæn/', pos: 'phr.', meaning: '〜よりむしろ', example: 'We chose speed rather than cost.', exampleJa: '費用よりも速さを選んだ。', level: 730, category: '頻出フレーズ' },
  { id: 190, word: 'come up with', phonetic: '/kʌm ʌp wɪð/', pos: 'phr.', meaning: '（案などを）思いつく', example: 'She came up with a clever solution.', exampleJa: '彼女は巧妙な解決策を思いついた。', level: 730, category: '頻出フレーズ' },

  // ===== 引っかかりやすい語 =====
  { id: 191, word: 'complement', phonetic: '/ˈkɒmplɪment/', pos: 'v.', meaning: '補完する（compliment「褒める」と混同注意）', example: 'The wine complements the meal nicely.', exampleJa: 'そのワインは料理をうまく引き立てる。', level: 860, category: '紛らわしい語' },
  { id: 192, word: 'considerable', phonetic: '/kənˈsɪdərəbl/', pos: 'adj.', meaning: 'かなりの（considerate「思いやりのある」と混同注意）', example: 'We spent a considerable amount of time on it.', exampleJa: 'それにかなりの時間を費やした。', level: 860, category: '紛らわしい語' },
  { id: 193, word: 'economical', phonetic: '/ˌiːkəˈnɒmɪkl/', pos: 'adj.', meaning: '経済的な、割安な（economic「経済の」と区別）', example: 'This car is more economical to run.', exampleJa: 'この車は維持費がより経済的だ。', level: 860, category: '紛らわしい語' },
  { id: 194, word: 'respectively', phonetic: '/rɪˈspektɪvli/', pos: 'adv.', meaning: 'それぞれ（respectfully「敬意を持って」と区別）', example: 'Sales rose 5 and 8 percent respectively.', exampleJa: '売上はそれぞれ5％と8％増加した。', level: 860, category: '紛らわしい語' },
  { id: 195, word: 'assure', phonetic: '/əˈʃʊə/', pos: 'v.', meaning: '（人に）保証する（ensure / insure と区別）', example: 'I assure you the data is accurate.', exampleJa: 'データが正確であることを保証します。', level: 860, category: '紛らわしい語' },
  { id: 196, word: 'adapt', phonetic: '/əˈdæpt/', pos: 'v.', meaning: '適応させる（adopt「採用する」と混同注意）', example: 'We adapted the software for local users.', exampleJa: '現地ユーザー向けにソフトを適応させた。', level: 860, category: '紛らわしい語' },
  { id: 197, word: 'effective', phonetic: '/ɪˈfektɪv/', pos: 'adj.', meaning: '効果的な、（規則が）発効して', example: 'The new policy is effective immediately.', exampleJa: '新方針は直ちに発効する。', level: 730, category: '紛らわしい語' },
  { id: 198, word: 'former', phonetic: '/ˈfɔːmə/', pos: 'adj.', meaning: '前の、以前の（latter「後者の」と対）', example: 'The former director now works abroad.', exampleJa: '前の部長は今は海外で働いている。', level: 730, category: '紛らわしい語' },
  { id: 199, word: 'alternative', phonetic: '/ɔːlˈtɜːnətɪv/', pos: 'n./adj.', meaning: '代替案／代わりの', example: 'Is there an alternative to this plan?', exampleJa: 'この計画に代わる案はありますか。', level: 730, category: '紛らわしい語' },
  { id: 200, word: 'beneficial', phonetic: '/ˌbenɪˈfɪʃl/', pos: 'adj.', meaning: '有益な', example: 'The training was beneficial to everyone.', exampleJa: 'その研修は全員にとって有益だった。', level: 730, category: '紛らわしい語' }
];

const LEVELS = [600, 730, 860];
const CATEGORIES = [...new Set(WORD_DATA.map((w) => w.category))];
