/**
 * 算数の問題データ — Ekamai International School (EIS) Grade 8 受験向け
 *
 * 入試は英語で出題されるため、問題文は英語・解説は日本語にしている。
 *
 * 各エントリの構造:
 *   id          : 一意なID（学習履歴の保存キー。単語と区別するため 'm' で始まる）
 *   question    : 問題文（英語）
 *   answer      : 答え（数値の文字列。単位は含めない）
 *   unit        : 入力欄の後ろに表示する単位（空でも可）
 *   explanation : 解き方の説明（日本語）
 *   level       : 難易度 (1=基礎 / 2=標準 / 3=応用)
 *   category    : 分野
 */
const MATH_DATA = [
  { id: 'm1', question: 'Calculate: 47 + 68', answer: '115', unit: '', explanation: '47 + 68 = 115。一の位 7+8=15 で1繰り上がり、十の位 4+6+1=11。', level: 1, category: '計算' },
  { id: 'm2', question: 'Calculate: 205 − 137', answer: '68', unit: '', explanation: '205 − 137 = 68。137 に 63 を足すと 200、さらに 5 で 68。', level: 1, category: '計算' },
  { id: 'm3', question: 'Calculate: 24 × 15', answer: '360', unit: '', explanation: '24 × 15 = 24 × 10 + 24 × 5 = 240 + 120 = 360。', level: 1, category: '計算' },
  { id: 'm4', question: 'Calculate: 456 ÷ 8', answer: '57', unit: '', explanation: '456 ÷ 8 = 57。8 × 50 = 400、残り 56 は 8 × 7。', level: 1, category: '計算' },
  { id: 'm5', question: 'Calculate: 6 + 3 × 4', answer: '18', unit: '', explanation: 'かけ算が先。3 × 4 = 12 を先に計算して 6 + 12 = 18。', level: 1, category: '計算' },
  { id: 'm6', question: 'Calculate: (8 + 4) ÷ 3', answer: '4', unit: '', explanation: 'かっこが先。8 + 4 = 12、12 ÷ 3 = 4。', level: 1, category: '計算' },
  { id: 'm7', question: 'Calculate: 5 × (9 − 3) ÷ 2', answer: '15', unit: '', explanation: 'かっこ → かけ算・わり算の順。9 − 3 = 6、5 × 6 = 30、30 ÷ 2 = 15。', level: 2, category: '計算' },
  { id: 'm8', question: 'Calculate: −7 + 12', answer: '5', unit: '', explanation: '−7 に 12 を足す。数直線で −7 から右へ 12 進むと 5。', level: 2, category: '計算' },
  { id: 'm9', question: 'Calculate: −6 − 9', answer: '-15', unit: '', explanation: '負の数からさらに引くので、絶対値を足して負にする。−(6 + 9) = −15。', level: 2, category: '計算' },
  { id: 'm10', question: 'Calculate: (−4) × (−5)', answer: '20', unit: '', explanation: '負 × 負 = 正。4 × 5 = 20 なので答えは 20。', level: 2, category: '計算' },
  { id: 'm11', question: 'Calculate: (−36) ÷ 9', answer: '-4', unit: '', explanation: '負 ÷ 正 = 負。36 ÷ 9 = 4 なので −4。', level: 2, category: '計算' },
  { id: 'm12', question: 'Calculate: 3² + 4²', answer: '25', unit: '', explanation: '3² = 9、4² = 16。9 + 16 = 25。', level: 2, category: '計算' },
  { id: 'm13', question: 'Calculate: the square root of 144', answer: '12', unit: '', explanation: '12 × 12 = 144 なので、144 の平方根は 12。', level: 2, category: '計算' },
  { id: 'm14', question: 'Calculate: 2 × 3² − 5', answer: '13', unit: '', explanation: '指数が先。3² = 9、2 × 9 = 18、18 − 5 = 13。', level: 3, category: '計算' },
  { id: 'm15', question: 'What is the value of 5³?', answer: '125', unit: '', explanation: '5³ = 5 × 5 × 5 = 125。', level: 3, category: '計算' },
  { id: 'm16', question: 'Find the greatest common factor of 24 and 36.', answer: '12', unit: '', explanation: '24 の約数と 36 の約数に共通する最大のものは 12（24 = 12 × 2、36 = 12 × 3）。', level: 3, category: '計算' },
  { id: 'm17', question: 'Find the least common multiple of 6 and 8.', answer: '24', unit: '', explanation: '6 の倍数 6,12,18,24… と 8 の倍数 8,16,24… で最初に一致するのは 24。', level: 3, category: '計算' },
  { id: 'm18', question: 'Calculate: 1/2 + 1/4 (write your answer as a decimal)', answer: '0.75', unit: '', explanation: '1/2 = 2/4 なので 2/4 + 1/4 = 3/4 = 0.75。', level: 1, category: '分数・小数' },
  { id: 'm19', question: 'Calculate: 3/5 of 40', answer: '24', unit: '', explanation: '40 ÷ 5 = 8、8 × 3 = 24。', level: 1, category: '分数・小数' },
  { id: 'm20', question: 'Calculate: 2/3 × 9', answer: '6', unit: '', explanation: '9 ÷ 3 = 3、3 × 2 = 6。', level: 1, category: '分数・小数' },
  { id: 'm21', question: 'Simplify 18/24 and write the numerator of the simplest form.', answer: '3', unit: '', explanation: '18 と 24 の最大公約数は 6。18 ÷ 6 = 3、24 ÷ 6 = 4 なので 3/4。分子は 3。', level: 2, category: '分数・小数' },
  { id: 'm22', question: 'Calculate: 0.4 × 0.3', answer: '0.12', unit: '', explanation: '4 × 3 = 12。小数点以下が合わせて2桁なので 0.12。', level: 2, category: '分数・小数' },
  { id: 'm23', question: 'Calculate: 7.2 ÷ 0.9', answer: '8', unit: '', explanation: '両方を10倍して 72 ÷ 9 = 8。', level: 2, category: '分数・小数' },
  { id: 'm24', question: 'Calculate: 1.25 + 3.7', answer: '4.95', unit: '', explanation: '小数点をそろえて 1.25 + 3.70 = 4.95。', level: 1, category: '分数・小数' },
  { id: 'm25', question: 'Round 3.678 to two decimal places.', answer: '3.68', unit: '', explanation: '小数第3位が 8 なので繰り上げて 3.68。', level: 2, category: '分数・小数' },
  { id: 'm26', question: 'Write 3/8 as a decimal.', answer: '0.375', unit: '', explanation: '3 ÷ 8 = 0.375。', level: 2, category: '分数・小数' },
  { id: 'm27', question: 'Write 0.6 as a fraction in simplest form. Give the denominator.', answer: '5', unit: '', explanation: '0.6 = 6/10。分母分子を2で割って 3/5。分母は 5。', level: 3, category: '分数・小数' },
  { id: 'm28', question: 'Calculate: 2/3 + 1/6 (write your answer as a decimal)', answer: '0.833', unit: '', explanation: '通分して 4/6 + 1/6 = 5/6 ≒ 0.833（小数第3位まで）。', level: 3, category: '分数・小数' },
  { id: 'm29', question: 'Calculate: 3/4 ÷ 1/2', answer: '1.5', unit: '', explanation: 'わり算は逆数のかけ算。3/4 × 2/1 = 6/4 = 1.5。', level: 3, category: '分数・小数' },
  { id: 'm30', question: 'What is 25% of 80?', answer: '20', unit: '', explanation: '25% は 1/4。80 ÷ 4 = 20。', level: 1, category: '割合・比' },
  { id: 'm31', question: 'What is 15% of 200?', answer: '30', unit: '', explanation: '10% が 20、5% が 10。合わせて 30。', level: 1, category: '割合・比' },
  { id: 'm32', question: 'A shirt costs 400 baht. It is 20% off. What is the new price in baht?', answer: '320', unit: '', explanation: '20% 引きは 80% の価格。400 × 0.8 = 320 バーツ。', level: 2, category: '割合・比' },
  { id: 'm33', question: '12 is what percent of 60? (Give the number only.)', answer: '20', unit: '', explanation: '12 ÷ 60 = 0.2 なので 20%。', level: 2, category: '割合・比' },
  { id: 'm34', question: 'The ratio of boys to girls is 3:2. There are 30 students in total. How many boys are there?', answer: '18', unit: '', explanation: '比の合計は 3 + 2 = 5。30 ÷ 5 = 6、男子は 6 × 3 = 18人。', level: 2, category: '割合・比' },
  { id: 'm35', question: 'A price rises from 50 to 65. What is the percentage increase? (Give the number only.)', answer: '30', unit: '', explanation: '増えた分は 15。15 ÷ 50 = 0.3 なので 30% の増加。', level: 3, category: '割合・比' },
  { id: 'm36', question: 'If 4 pens cost 60 baht, how much do 7 pens cost in baht?', answer: '105', unit: '', explanation: '1本 60 ÷ 4 = 15 バーツ。15 × 7 = 105 バーツ。', level: 2, category: '割合・比' },
  { id: 'm37', question: 'Solve the proportion: 3/4 = x/20. Find x.', answer: '15', unit: '', explanation: '両辺に 20 をかけて x = 20 × 3 ÷ 4 = 15。', level: 3, category: '割合・比' },
  { id: 'm38', question: 'A map scale is 1:50000. A distance of 3 cm on the map is how many kilometers in real life?', answer: '1.5', unit: '', explanation: '3 cm × 50000 = 150000 cm = 1500 m = 1.5 km。', level: 3, category: '割合・比' },
  { id: 'm39', question: 'After a 10% discount, a book costs 270 baht. What was the original price in baht?', answer: '300', unit: '', explanation: '270 は元の値段の 90%。270 ÷ 0.9 = 300 バーツ。', level: 3, category: '割合・比' },
  { id: 'm40', question: 'What percentage is 45 out of 180? (Give the number only.)', answer: '25', unit: '', explanation: '45 ÷ 180 = 0.25 なので 25%。', level: 2, category: '割合・比' },
  { id: 'm41', question: 'Increase 250 by 12%.', answer: '280', unit: '', explanation: '250 × 0.12 = 30。250 + 30 = 280。', level: 3, category: '割合・比' },
  { id: 'm42', question: 'Solve for x: x + 7 = 19', answer: '12', unit: '', explanation: '両辺から 7 を引いて x = 19 − 7 = 12。', level: 1, category: '方程式' },
  { id: 'm43', question: 'Solve for x: 5x = 45', answer: '9', unit: '', explanation: '両辺を 5 で割って x = 45 ÷ 5 = 9。', level: 1, category: '方程式' },
  { id: 'm44', question: 'Solve for x: x ÷ 4 = 8', answer: '32', unit: '', explanation: '両辺に 4 をかけて x = 8 × 4 = 32。', level: 1, category: '方程式' },
  { id: 'm45', question: 'Solve for x: 3x + 5 = 20', answer: '5', unit: '', explanation: '両辺から 5 を引いて 3x = 15、両辺を 3 で割って x = 5。', level: 2, category: '方程式' },
  { id: 'm46', question: 'Solve for x: 2x − 9 = 13', answer: '11', unit: '', explanation: '両辺に 9 を足して 2x = 22、両辺を 2 で割って x = 11。', level: 2, category: '方程式' },
  { id: 'm47', question: 'Solve for x: 4(x − 2) = 20', answer: '7', unit: '', explanation: '両辺を 4 で割って x − 2 = 5、よって x = 7。', level: 2, category: '方程式' },
  { id: 'm48', question: 'Solve for x: 7x − 3 = 4x + 12', answer: '5', unit: '', explanation: '両辺から 4x を引いて 3x − 3 = 12、3x = 15、x = 5。', level: 3, category: '方程式' },
  { id: 'm49', question: 'If y = 3x + 2, what is y when x = 4?', answer: '14', unit: '', explanation: 'x に 4 を代入して y = 3 × 4 + 2 = 14。', level: 2, category: '方程式' },
  { id: 'm50', question: 'Simplify: 5x + 3x − 2x. Give the coefficient of x.', answer: '6', unit: '', explanation: '5 + 3 − 2 = 6 なので 6x。係数は 6。', level: 2, category: '方程式' },
  { id: 'm51', question: 'Solve for x: x/3 + 4 = 10', answer: '18', unit: '', explanation: '両辺から 4 を引いて x/3 = 6、両辺に 3 をかけて x = 18。', level: 3, category: '方程式' },
  { id: 'm52', question: 'The sum of three consecutive numbers is 48. What is the smallest one?', answer: '15', unit: '', explanation: '真ん中を x とすると 3x = 48、x = 16。3数は 15, 16, 17 なので最小は 15。', level: 3, category: '方程式' },
  { id: 'm53', question: 'If 2x + y = 14 and y = 4, what is x?', answer: '5', unit: '', explanation: 'y に 4 を代入して 2x + 4 = 14、2x = 10、x = 5。', level: 3, category: '方程式' },
  { id: 'm54', question: 'A rectangle is 8 cm long and 5 cm wide. What is its area in cm²?', answer: '40', unit: 'cm²', explanation: '長方形の面積 = 縦 × 横 = 8 × 5 = 40 cm²。', level: 1, category: '図形' },
  { id: 'm55', question: 'A rectangle is 8 cm long and 5 cm wide. What is its perimeter in cm?', answer: '26', unit: 'cm', explanation: '周の長さ = (縦 + 横) × 2 = (8 + 5) × 2 = 26 cm。', level: 1, category: '図形' },
  { id: 'm56', question: 'A square has a side of 7 cm. What is its area in cm²?', answer: '49', unit: 'cm²', explanation: '正方形の面積 = 1辺 × 1辺 = 7 × 7 = 49 cm²。', level: 1, category: '図形' },
  { id: 'm57', question: 'A triangle has a base of 10 cm and a height of 6 cm. What is its area in cm²?', answer: '30', unit: 'cm²', explanation: '三角形の面積 = 底辺 × 高さ ÷ 2 = 10 × 6 ÷ 2 = 30 cm²。', level: 2, category: '図形' },
  { id: 'm58', question: 'A circle has a radius of 5 cm. What is its diameter in cm?', answer: '10', unit: 'cm', explanation: '直径 = 半径 × 2 = 5 × 2 = 10 cm。', level: 1, category: '図形' },
  { id: 'm59', question: 'The angles of a triangle are 50° and 60°. What is the third angle in degrees?', answer: '70', unit: '°', explanation: '三角形の内角の和は 180°。180 − 50 − 60 = 70°。', level: 2, category: '図形' },
  { id: 'm60', question: 'A cube has a side of 4 cm. What is its volume in cm³?', answer: '64', unit: 'cm³', explanation: '立方体の体積 = 1辺³ = 4 × 4 × 4 = 64 cm³。', level: 2, category: '図形' },
  { id: 'm61', question: 'A box is 5 cm × 3 cm × 2 cm. What is its volume in cm³?', answer: '30', unit: 'cm³', explanation: '直方体の体積 = 縦 × 横 × 高さ = 5 × 3 × 2 = 30 cm³。', level: 2, category: '図形' },
  { id: 'm62', question: 'Two angles on a straight line are 115° and x. What is x in degrees?', answer: '65', unit: '°', explanation: '直線上の角の和は 180°。180 − 115 = 65°。', level: 2, category: '図形' },
  { id: 'm63', question: 'The area of a square is 81 cm². What is the length of one side in cm?', answer: '9', unit: 'cm', explanation: '9 × 9 = 81 なので 1辺は 9 cm。', level: 3, category: '図形' },
  { id: 'm64', question: 'A parallelogram has a base of 12 cm and a height of 7 cm. What is its area in cm²?', answer: '84', unit: 'cm²', explanation: '平行四辺形の面積 = 底辺 × 高さ = 12 × 7 = 84 cm²。', level: 3, category: '図形' },
  { id: 'm65', question: 'What is the sum of the interior angles of a quadrilateral, in degrees?', answer: '360', unit: '°', explanation: '四角形は三角形2つ分なので 180 × 2 = 360°。', level: 3, category: '図形' },
  { id: 'm66', question: 'A triangle has an area of 24 cm² and a base of 8 cm. What is its height in cm?', answer: '6', unit: 'cm', explanation: '面積 = 底辺 × 高さ ÷ 2 なので、高さ = 24 × 2 ÷ 8 = 6 cm。', level: 3, category: '図形' },
  { id: 'm67', question: 'A car travels 240 km in 3 hours. What is its speed in km per hour?', answer: '80', unit: 'km/h', explanation: '速さ = 距離 ÷ 時間 = 240 ÷ 3 = 80 km/h。', level: 2, category: '文章題' },
  { id: 'm68', question: 'A train travels at 60 km/h for 2.5 hours. How far does it go in km?', answer: '150', unit: 'km', explanation: '距離 = 速さ × 時間 = 60 × 2.5 = 150 km。', level: 2, category: '文章題' },
  { id: 'm69', question: 'Ann has 350 baht. She buys 3 notebooks at 45 baht each. How much money is left in baht?', answer: '215', unit: 'baht', explanation: 'ノート代は 45 × 3 = 135 バーツ。350 − 135 = 215 バーツ。', level: 1, category: '文章題' },
  { id: 'm70', question: 'A class of 32 students is divided into groups of 4. How many groups are there?', answer: '8', unit: '', explanation: '32 ÷ 4 = 8 グループ。', level: 1, category: '文章題' },
  { id: 'm71', question: 'A book has 240 pages. Tom has read 3/8 of it. How many pages has he read?', answer: '90', unit: 'pages', explanation: '240 ÷ 8 = 30、30 × 3 = 90 ページ。', level: 2, category: '文章題' },
  { id: 'm72', question: 'A school day starts at 8:15 and ends at 15:45. How many minutes long is it?', answer: '450', unit: 'minutes', explanation: '8:15 から 15:45 までは 7 時間 30 分。7 × 60 + 30 = 450 分。', level: 2, category: '文章題' },
  { id: 'm73', question: 'Five friends share 2 kg of candy equally. How many grams does each get?', answer: '400', unit: 'g', explanation: '2 kg = 2000 g。2000 ÷ 5 = 400 g。', level: 2, category: '文章題' },
  { id: 'm74', question: 'A tank holds 45 liters. It is 2/3 full. How many liters are in it?', answer: '30', unit: 'L', explanation: '45 ÷ 3 = 15、15 × 2 = 30 リットル。', level: 2, category: '文章題' },
  { id: 'm75', question: 'A shop sells pens for 12 baht each. How many pens can you buy with 100 baht?', answer: '8', unit: 'pens', explanation: '100 ÷ 12 = 8 あまり 4。買えるのは 8 本。', level: 3, category: '文章題' },
  { id: 'm76', question: 'Three workers build a wall in 12 days. How many days would 4 workers take at the same rate?', answer: '9', unit: 'days', explanation: '仕事量は 3 × 12 = 36 人日。36 ÷ 4 = 9 日。', level: 3, category: '文章題' },
  { id: 'm77', question: 'The average of 4 numbers is 15. What is their total?', answer: '60', unit: '', explanation: '合計 = 平均 × 個数 = 15 × 4 = 60。', level: 2, category: '文章題' },
  { id: 'm78', question: 'A rope 3.6 m long is cut into 8 equal pieces. How long is each piece in cm?', answer: '45', unit: 'cm', explanation: '3.6 m = 360 cm。360 ÷ 8 = 45 cm。', level: 3, category: '文章題' },
  { id: 'm79', question: 'Find the mean of 4, 7, 9, and 12.', answer: '8', unit: '', explanation: '合計 32 ÷ 個数 4 = 8。', level: 1, category: 'データ' },
  { id: 'm80', question: 'Find the median of 3, 8, 5, 11, 6.', answer: '6', unit: '', explanation: '小さい順に 3, 5, 6, 8, 11。真ん中は 6。', level: 2, category: 'データ' },
  { id: 'm81', question: 'Find the mode of 2, 5, 3, 5, 7, 5.', answer: '5', unit: '', explanation: '最も多く出てくる数は 5（3回）。', level: 2, category: 'データ' },
  { id: 'm82', question: 'Find the range of 14, 8, 21, 5.', answer: '16', unit: '', explanation: '範囲 = 最大 − 最小 = 21 − 5 = 16。', level: 2, category: 'データ' },
  { id: 'm83', question: 'A bag has 3 red and 5 blue balls. What is the probability of picking a red one? Write it as a decimal.', answer: '0.375', unit: '', explanation: '全部で 8 個のうち赤は 3 個。3 ÷ 8 = 0.375。', level: 3, category: 'データ' },
  { id: 'm84', question: 'A die is rolled once. What is the probability of getting a number greater than 4? Write it as a decimal to two places.', answer: '0.33', unit: '', explanation: '5 と 6 の 2 通り。2 ÷ 6 = 0.333… なので小数第2位で 0.33。', level: 3, category: 'データ' },
  { id: 'm85', question: 'The mean of 5 numbers is 12. One number is removed and the mean becomes 13. What number was removed?', answer: '8', unit: '', explanation: '元の合計は 60、残り4個の合計は 52。60 − 52 = 8。', level: 3, category: 'データ' },
  { id: 'm86', question: 'In a class of 25, 60% are girls. How many girls are there?', answer: '15', unit: '', explanation: '25 × 0.6 = 15人。', level: 2, category: 'データ' }
];

const MATH_CATEGORIES = [...new Set(MATH_DATA.map((p) => p.category))];
