/**
 * 算数・数学の問題データ — Ekamai International School (EIS) Grade 8 受験向け
 *
 * 範囲は小学校の復習から中学1年まで。単元は日本の中1数学の並びに合わせている。
 * 入試は英語で出題されるため、問題文は英語・解説は日本語にしている。
 *
 * 各エントリの構造:
 *   id          : 一意なID（学習履歴の保存キー。単語と区別するため 'm' で始まる）
 *   question    : 問題文（英語）
 *   answer      : 答え（数値の文字列。単位は含めない）
 *   unit        : 入力欄の後ろに表示する単位（空でも可）
 *   explanation : 解き方の説明（日本語）
 *   level       : 1=小学の復習 / 2=中1の基本 / 3=中1の発展
 *   category    : 単元
 */
const MATH_DATA = [
  { id: 'm1', question: 'Calculate: 47 + 68', answer: '115', unit: '', explanation: '47 + 68 = 115。一の位 7+8=15 で1繰り上がり、十の位 4+6+1=11。', level: 1, category: '四則計算' },
  { id: 'm2', question: 'Calculate: 24 × 15', answer: '360', unit: '', explanation: '24 × 15 = 24 × 10 + 24 × 5 = 240 + 120 = 360。', level: 1, category: '四則計算' },
  { id: 'm3', question: 'Calculate: 456 ÷ 8', answer: '57', unit: '', explanation: '456 ÷ 8 = 57。8 × 50 = 400、残り 56 は 8 × 7。', level: 1, category: '四則計算' },
  { id: 'm4', question: 'Calculate: 6 + 3 × 4', answer: '18', unit: '', explanation: 'かけ算が先。3 × 4 = 12 を先に計算して 6 + 12 = 18。', level: 1, category: '四則計算' },
  { id: 'm5', question: 'Calculate: (8 + 4) ÷ 3', answer: '4', unit: '', explanation: 'かっこが先。8 + 4 = 12、12 ÷ 3 = 4。', level: 1, category: '四則計算' },
  { id: 'm6', question: 'Calculate: 3² + 4²', answer: '25', unit: '', explanation: '3² = 9、4² = 16。9 + 16 = 25。', level: 2, category: '四則計算' },
  { id: 'm7', question: 'What is the value of 5³?', answer: '125', unit: '', explanation: '5³ = 5 × 5 × 5 = 125。', level: 3, category: '四則計算' },
  { id: 'm8', question: 'Find the greatest common factor of 24 and 36.', answer: '12', unit: '', explanation: '24 の約数と 36 の約数に共通する最大のものは 12（24 = 12 × 2、36 = 12 × 3）。', level: 3, category: '四則計算' },
  { id: 'm9', question: 'Find the least common multiple of 6 and 8.', answer: '24', unit: '', explanation: '6 の倍数 6,12,18,24… と 8 の倍数 8,16,24… で最初に一致するのは 24。', level: 3, category: '四則計算' },
  { id: 'm10', question: 'Calculate: 1/2 + 1/4 (write your answer as a decimal)', answer: '0.75', unit: '', explanation: '1/2 = 2/4 なので 2/4 + 1/4 = 3/4 = 0.75。', level: 1, category: '分数・小数' },
  { id: 'm11', question: 'Calculate: 3/5 of 40', answer: '24', unit: '', explanation: '40 ÷ 5 = 8、8 × 3 = 24。', level: 1, category: '分数・小数' },
  { id: 'm12', question: 'Calculate: 2/3 × 9', answer: '6', unit: '', explanation: '9 ÷ 3 = 3、3 × 2 = 6。', level: 1, category: '分数・小数' },
  { id: 'm13', question: 'Calculate: 1.25 + 3.7', answer: '4.95', unit: '', explanation: '小数点をそろえて 1.25 + 3.70 = 4.95。', level: 1, category: '分数・小数' },
  { id: 'm14', question: 'Simplify 18/24 and write the numerator of the simplest form.', answer: '3', unit: '', explanation: '18 と 24 の最大公約数は 6。18 ÷ 6 = 3、24 ÷ 6 = 4 なので 3/4。分子は 3。', level: 2, category: '分数・小数' },
  { id: 'm15', question: 'Calculate: 0.4 × 0.3', answer: '0.12', unit: '', explanation: '4 × 3 = 12。小数点以下が合わせて2桁なので 0.12。', level: 2, category: '分数・小数' },
  { id: 'm16', question: 'Calculate: 7.2 ÷ 0.9', answer: '8', unit: '', explanation: '両方を10倍して 72 ÷ 9 = 8。', level: 2, category: '分数・小数' },
  { id: 'm17', question: 'Round 3.678 to two decimal places.', answer: '3.68', unit: '', explanation: '小数第3位が 8 なので繰り上げて 3.68。', level: 2, category: '分数・小数' },
  { id: 'm18', question: 'Write 3/8 as a decimal.', answer: '0.375', unit: '', explanation: '3 ÷ 8 = 0.375。', level: 2, category: '分数・小数' },
  { id: 'm19', question: 'Write 0.6 as a fraction in simplest form. Give the denominator.', answer: '5', unit: '', explanation: '0.6 = 6/10。分母分子を2で割って 3/5。分母は 5。', level: 3, category: '分数・小数' },
  { id: 'm20', question: 'Calculate: 2/3 + 1/6 (write your answer as a decimal)', answer: '0.833', unit: '', explanation: '通分して 4/6 + 1/6 = 5/6 ≒ 0.833（小数第3位まで）。', level: 3, category: '分数・小数' },
  { id: 'm21', question: 'Calculate: 3/4 ÷ 1/2', answer: '1.5', unit: '', explanation: 'わり算は逆数のかけ算。3/4 × 2/1 = 6/4 = 1.5。', level: 3, category: '分数・小数' },
  { id: 'm22', question: 'What is 25% of 80?', answer: '20', unit: '', explanation: '25% は 1/4。80 ÷ 4 = 20。', level: 1, category: '割合と比' },
  { id: 'm23', question: 'What is 15% of 200?', answer: '30', unit: '', explanation: '10% が 20、5% が 10。合わせて 30。', level: 1, category: '割合と比' },
  { id: 'm24', question: 'A shirt costs 400 baht. It is 20% off. What is the new price in baht?', answer: '320', unit: '', explanation: '20% 引きは 80% の価格。400 × 0.8 = 320 バーツ。', level: 2, category: '割合と比' },
  { id: 'm25', question: '12 is what percent of 60? (Give the number only.)', answer: '20', unit: '', explanation: '12 ÷ 60 = 0.2 なので 20%。', level: 2, category: '割合と比' },
  { id: 'm26', question: 'The ratio of boys to girls is 3:2. There are 30 students in total. How many boys are there?', answer: '18', unit: '', explanation: '比の合計は 3 + 2 = 5。30 ÷ 5 = 6、男子は 6 × 3 = 18人。', level: 2, category: '割合と比' },
  { id: 'm27', question: 'If 4 pens cost 60 baht, how much do 7 pens cost in baht?', answer: '105', unit: '', explanation: '1本 60 ÷ 4 = 15 バーツ。15 × 7 = 105 バーツ。', level: 2, category: '割合と比' },
  { id: 'm28', question: 'What percentage is 45 out of 180? (Give the number only.)', answer: '25', unit: '', explanation: '45 ÷ 180 = 0.25 なので 25%。', level: 2, category: '割合と比' },
  { id: 'm29', question: 'A price rises from 50 to 65. What is the percentage increase? (Give the number only.)', answer: '30', unit: '', explanation: '増えた分は 15。15 ÷ 50 = 0.3 なので 30% の増加。', level: 3, category: '割合と比' },
  { id: 'm30', question: 'Solve the proportion: 3/4 = x/20. Find x.', answer: '15', unit: '', explanation: '両辺に 20 をかけて x = 20 × 3 ÷ 4 = 15。', level: 3, category: '割合と比' },
  { id: 'm31', question: 'A map scale is 1:50000. A distance of 3 cm on the map is how many kilometers in real life?', answer: '1.5', unit: '', explanation: '3 cm × 50000 = 150000 cm = 1500 m = 1.5 km。', level: 3, category: '割合と比' },
  { id: 'm32', question: 'After a 10% discount, a book costs 270 baht. What was the original price in baht?', answer: '300', unit: '', explanation: '270 は元の値段の 90%。270 ÷ 0.9 = 300 バーツ。', level: 3, category: '割合と比' },
  { id: 'm33', question: 'Increase 250 by 12%.', answer: '280', unit: '', explanation: '250 × 0.12 = 30。250 + 30 = 280。', level: 3, category: '割合と比' },
  { id: 'm34', question: 'Ann has 350 baht. She buys 3 notebooks at 45 baht each. How much money is left in baht?', answer: '215', unit: 'baht', explanation: 'ノート代は 45 × 3 = 135 バーツ。350 − 135 = 215 バーツ。', level: 1, category: '速さ・文章題' },
  { id: 'm35', question: 'A class of 32 students is divided into groups of 4. How many groups are there?', answer: '8', unit: '', explanation: '32 ÷ 4 = 8 グループ。', level: 1, category: '速さ・文章題' },
  { id: 'm36', question: 'A car travels 240 km in 3 hours. What is its speed in km per hour?', answer: '80', unit: 'km/h', explanation: '速さ = 距離 ÷ 時間 = 240 ÷ 3 = 80 km/h。', level: 2, category: '速さ・文章題' },
  { id: 'm37', question: 'A train travels at 60 km/h for 2.5 hours. How far does it go in km?', answer: '150', unit: 'km', explanation: '距離 = 速さ × 時間 = 60 × 2.5 = 150 km。', level: 2, category: '速さ・文章題' },
  { id: 'm38', question: 'A book has 240 pages. Tom has read 3/8 of it. How many pages has he read?', answer: '90', unit: 'pages', explanation: '240 ÷ 8 = 30、30 × 3 = 90 ページ。', level: 2, category: '速さ・文章題' },
  { id: 'm39', question: 'A school day starts at 8:15 and ends at 15:45. How many minutes long is it?', answer: '450', unit: 'minutes', explanation: '8:15 から 15:45 までは 7 時間 30 分。7 × 60 + 30 = 450 分。', level: 2, category: '速さ・文章題' },
  { id: 'm40', question: 'Five friends share 2 kg of candy equally. How many grams does each get?', answer: '400', unit: 'g', explanation: '2 kg = 2000 g。2000 ÷ 5 = 400 g。', level: 2, category: '速さ・文章題' },
  { id: 'm41', question: 'A tank holds 45 liters. It is 2/3 full. How many liters are in it?', answer: '30', unit: 'L', explanation: '45 ÷ 3 = 15、15 × 2 = 30 リットル。', level: 2, category: '速さ・文章題' },
  { id: 'm42', question: 'The average of 4 numbers is 15. What is their total?', answer: '60', unit: '', explanation: '合計 = 平均 × 個数 = 15 × 4 = 60。', level: 2, category: '速さ・文章題' },
  { id: 'm43', question: 'A shop sells pens for 12 baht each. How many pens can you buy with 100 baht?', answer: '8', unit: 'pens', explanation: '100 ÷ 12 = 8 あまり 4。買えるのは 8 本。', level: 3, category: '速さ・文章題' },
  { id: 'm44', question: 'Three workers build a wall in 12 days. How many days would 4 workers take at the same rate?', answer: '9', unit: 'days', explanation: '仕事量は 3 × 12 = 36 人日。36 ÷ 4 = 9 日。', level: 3, category: '速さ・文章題' },
  { id: 'm45', question: 'A rope 3.6 m long is cut into 8 equal pieces. How long is each piece in cm?', answer: '45', unit: 'cm', explanation: '3.6 m = 360 cm。360 ÷ 8 = 45 cm。', level: 3, category: '速さ・文章題' },
  { id: 'm46', question: 'Calculate: 205 − 137', answer: '68', unit: '', explanation: '205 − 137 = 68。137 に 63 を足すと 200、さらに 5 で 68。', level: 2, category: '正負の数' },
  { id: 'm47', question: 'Calculate: 5 × (9 − 3) ÷ 2', answer: '15', unit: '', explanation: 'かっこ → かけ算・わり算の順。9 − 3 = 6、5 × 6 = 30、30 ÷ 2 = 15。', level: 2, category: '正負の数' },
  { id: 'm48', question: 'Calculate: −7 + 12', answer: '5', unit: '', explanation: '−7 に 12 を足す。数直線で −7 から右へ 12 進むと 5。', level: 2, category: '正負の数' },
  { id: 'm49', question: 'Calculate: −6 − 9', answer: '-15', unit: '', explanation: '負の数からさらに引くので、絶対値を足して負にする。−(6 + 9) = −15。', level: 2, category: '正負の数' },
  { id: 'm50', question: 'Calculate: (−4) × (−5)', answer: '20', unit: '', explanation: '負 × 負 = 正。4 × 5 = 20 なので答えは 20。', level: 2, category: '正負の数' },
  { id: 'm51', question: 'Calculate: (−36) ÷ 9', answer: '-4', unit: '', explanation: '負 ÷ 正 = 負。36 ÷ 9 = 4 なので −4。', level: 2, category: '正負の数' },
  { id: 'm52', question: 'Calculate: 2 × 3² − 5', answer: '13', unit: '', explanation: '指数が先。3² = 9、2 × 9 = 18、18 − 5 = 13。', level: 2, category: '正負の数' },
  { id: 'm53', question: 'What is the absolute value of −8?', answer: '8', unit: '', explanation: '絶対値は数直線上での0からの距離。符号を取って 8。', level: 2, category: '正負の数' },
  { id: 'm54', question: 'Which is greater: −3 or −7? Write the greater number.', answer: '-3', unit: '', explanation: '負の数は絶対値が小さいほど大きい。数直線で右にある −3 が大きい。', level: 2, category: '正負の数' },
  { id: 'm55', question: 'Calculate: (−5) + (−8)', answer: '-13', unit: '', explanation: '同じ符号どうしの足し算は絶対値を足して同じ符号をつける。−(5+8) = −13。', level: 2, category: '正負の数' },
  { id: 'm56', question: 'Calculate: 9 + (−15)', answer: '-6', unit: '', explanation: '異符号の足し算は絶対値の差に、絶対値の大きい方の符号。15 − 9 = 6 で負なので −6。', level: 2, category: '正負の数' },
  { id: 'm57', question: 'Calculate: (−12) − (−4)', answer: '-8', unit: '', explanation: '引くことは符号を変えて足すこと。−12 + 4 = −8。', level: 2, category: '正負の数' },
  { id: 'm58', question: 'Calculate: 7 − (−6)', answer: '13', unit: '', explanation: '−(−6) は +6 になる。7 + 6 = 13。', level: 2, category: '正負の数' },
  { id: 'm59', question: 'Calculate: (−3) × 7', answer: '-21', unit: '', explanation: '負 × 正 = 負。3 × 7 = 21 なので −21。', level: 2, category: '正負の数' },
  { id: 'm60', question: 'Calculate: (−48) ÷ (−6)', answer: '8', unit: '', explanation: '負 ÷ 負 = 正。48 ÷ 6 = 8。', level: 2, category: '正負の数' },
  { id: 'm61', question: 'The temperature was −3°C in the morning and rose by 11°C. What is the temperature now in °C?', answer: '8', unit: '°C', explanation: '−3 + 11 = 8。数直線で −3 から右へ 11 進む。', level: 2, category: '正負の数' },
  { id: 'm62', question: 'Calculate: (−2)³', answer: '-8', unit: '', explanation: '(−2)×(−2)×(−2)。負の数を奇数回かけると負。−8。', level: 3, category: '正負の数' },
  { id: 'm63', question: 'Calculate: (−3)²', answer: '9', unit: '', explanation: '(−3)×(−3) = 9。かっこがあるので符号も2乗する点に注意。', level: 3, category: '正負の数' },
  { id: 'm64', question: 'Calculate: −4²', answer: '-16', unit: '', explanation: 'かっこがないので 4 だけを2乗して符号をつける。−(4×4) = −16。(−4)² = 16 との違いに注意。', level: 3, category: '正負の数' },
  { id: 'm65', question: 'Calculate: 5 − 3 × (−2)', answer: '11', unit: '', explanation: 'かけ算が先。3 × (−2) = −6。5 − (−6) = 5 + 6 = 11。', level: 3, category: '正負の数' },
  { id: 'm66', question: 'Calculate: (−18) ÷ 3 + 2 × (−4)', answer: '-14', unit: '', explanation: '−6 + (−8) = −14。わり算・かけ算を先に計算する。', level: 3, category: '正負の数' },
  { id: 'm67', question: 'Write 60 as a product of prime factors. What is the largest prime factor?', answer: '5', unit: '', explanation: '60 = 2² × 3 × 5。素因数は 2, 3, 5 で最大は 5。', level: 3, category: '正負の数' },
  { id: 'm68', question: 'If y = 3x + 2, what is y when x = 4?', answer: '14', unit: '', explanation: 'x に 4 を代入して y = 3 × 4 + 2 = 14。', level: 2, category: '文字と式' },
  { id: 'm69', question: 'Simplify: 5x + 3x − 2x. Give the coefficient of x.', answer: '6', unit: '', explanation: '5 + 3 − 2 = 6 なので 6x。係数は 6。', level: 2, category: '文字と式' },
  { id: 'm70', question: 'Write the expression for "5 times x, plus 3". If x = 4, what is the value?', answer: '23', unit: '', explanation: '式は 5x + 3。x に 4 を代入して 20 + 3 = 23。', level: 2, category: '文字と式' },
  { id: 'm71', question: 'If a = 3 and b = −2, find the value of 2a + b.', answer: '4', unit: '', explanation: '2 × 3 + (−2) = 6 − 2 = 4。', level: 2, category: '文字と式' },
  { id: 'm72', question: 'If x = −5, find the value of 3x − 4.', answer: '-19', unit: '', explanation: '3 × (−5) = −15。−15 − 4 = −19。', level: 2, category: '文字と式' },
  { id: 'm73', question: 'Simplify 7x − 2x + 4x. Give the coefficient of x.', answer: '9', unit: '', explanation: '同類項をまとめる。7 − 2 + 4 = 9 なので 9x。', level: 2, category: '文字と式' },
  { id: 'm74', question: 'Expand 3(2x + 5) and give the constant term.', answer: '15', unit: '', explanation: '分配法則で 6x + 15。定数項は 15。', level: 2, category: '文字と式' },
  { id: 'm75', question: 'A pen costs x baht. What is the total cost of 6 pens when x = 25? (Give the number only.)', answer: '150', unit: '', explanation: '式は 6x。x = 25 を代入して 150 バーツ。', level: 2, category: '文字と式' },
  { id: 'm76', question: 'The perimeter of a square with side a is 4a. If the perimeter is 36 cm, what is a in cm?', answer: '9', unit: 'cm', explanation: '4a = 36 なので a = 9 cm。', level: 2, category: '文字と式' },
  { id: 'm77', question: 'If y = 2x − 1, what is y when x = 0?', answer: '-1', unit: '', explanation: 'x に 0 を代入して y = 0 − 1 = −1。', level: 2, category: '文字と式' },
  { id: 'm78', question: 'The cost of x books at 250 baht each plus a 100 baht bag is 250x + 100. Find the cost when x = 3.', answer: '850', unit: 'baht', explanation: '250 × 3 + 100 = 850 バーツ。', level: 2, category: '文字と式' },
  { id: 'm79', question: 'If x = 2, find the value of x² + 3x.', answer: '10', unit: '', explanation: '2² = 4、3 × 2 = 6。4 + 6 = 10。', level: 3, category: '文字と式' },
  { id: 'm80', question: 'Simplify 4(x + 2) − 3x. Give the coefficient of x.', answer: '1', unit: '', explanation: '4x + 8 − 3x = x + 8。x の係数は 1。', level: 3, category: '文字と式' },
  { id: 'm81', question: 'A number is x. Write "3 less than twice the number" and find its value when x = 10.', answer: '17', unit: '', explanation: '式は 2x − 3。x = 10 で 20 − 3 = 17。', level: 3, category: '文字と式' },
  { id: 'm82', question: 'If a = −4, find the value of −2a.', answer: '8', unit: '', explanation: '−2 × (−4) = 8。負 × 負 = 正。', level: 3, category: '文字と式' },
  { id: 'm83', question: 'Simplify 5x + 3 − 2x − 8. Give the constant term.', answer: '-5', unit: '', explanation: '3x − 5 になる。定数項は 3 − 8 = −5。', level: 3, category: '文字と式' },
  { id: 'm84', question: 'Solve for x: x + 7 = 19', answer: '12', unit: '', explanation: '両辺から 7 を引いて x = 19 − 7 = 12。', level: 1, category: '一次方程式' },
  { id: 'm85', question: 'Solve for x: 5x = 45', answer: '9', unit: '', explanation: '両辺を 5 で割って x = 45 ÷ 5 = 9。', level: 1, category: '一次方程式' },
  { id: 'm86', question: 'Solve for x: x ÷ 4 = 8', answer: '32', unit: '', explanation: '両辺に 4 をかけて x = 8 × 4 = 32。', level: 1, category: '一次方程式' },
  { id: 'm87', question: 'Solve for x: 3x + 5 = 20', answer: '5', unit: '', explanation: '両辺から 5 を引いて 3x = 15、両辺を 3 で割って x = 5。', level: 2, category: '一次方程式' },
  { id: 'm88', question: 'Solve for x: 2x − 9 = 13', answer: '11', unit: '', explanation: '両辺に 9 を足して 2x = 22、両辺を 2 で割って x = 11。', level: 2, category: '一次方程式' },
  { id: 'm89', question: 'Solve for x: 4(x − 2) = 20', answer: '7', unit: '', explanation: '両辺を 4 で割って x − 2 = 5、よって x = 7。', level: 2, category: '一次方程式' },
  { id: 'm90', question: 'Solve for x: 7x − 3 = 4x + 12', answer: '5', unit: '', explanation: '両辺から 4x を引いて 3x − 3 = 12、3x = 15、x = 5。', level: 3, category: '一次方程式' },
  { id: 'm91', question: 'Solve for x: x/3 + 4 = 10', answer: '18', unit: '', explanation: '両辺から 4 を引いて x/3 = 6、両辺に 3 をかけて x = 18。', level: 3, category: '一次方程式' },
  { id: 'm92', question: 'The sum of three consecutive numbers is 48. What is the smallest one?', answer: '15', unit: '', explanation: '真ん中を x とすると 3x = 48、x = 16。3数は 15, 16, 17 なので最小は 15。', level: 3, category: '一次方程式' },
  { id: 'm93', question: 'If 2x + y = 14 and y = 4, what is x?', answer: '5', unit: '', explanation: 'y に 4 を代入して 2x + 4 = 14、2x = 10、x = 5。', level: 3, category: '一次方程式' },
  { id: 'm94', question: 'y is proportional to x, and y = 12 when x = 3. Find the constant of proportionality.', answer: '4', unit: '', explanation: 'y = ax に代入して 12 = 3a、a = 4。', level: 2, category: '比例と反比例' },
  { id: 'm95', question: 'y = 5x. Find y when x = 7.', answer: '35', unit: '', explanation: 'x に 7 を代入して y = 35。', level: 2, category: '比例と反比例' },
  { id: 'm96', question: 'y = 3x. Find x when y = 24.', answer: '8', unit: '', explanation: '24 = 3x なので x = 8。', level: 2, category: '比例と反比例' },
  { id: 'm97', question: 'y = 36/x. Find y when x = 9.', answer: '4', unit: '', explanation: '36 ÷ 9 = 4。', level: 2, category: '比例と反比例' },
  { id: 'm98', question: 'A car uses 8 liters of fuel for 100 km. How many liters does it use for 250 km?', answer: '20', unit: 'L', explanation: '比例の関係。1 km あたり 0.08 L。0.08 × 250 = 20 L。', level: 2, category: '比例と反比例' },
  { id: 'm99', question: 'Point A has coordinates (3, −2). What is its y-coordinate?', answer: '-2', unit: '', explanation: '座標は (x, y) の順。y 座標は −2。', level: 2, category: '比例と反比例' },
  { id: 'm100', question: 'y is inversely proportional to x, and y = 6 when x = 4. Find the constant.', answer: '24', unit: '', explanation: '反比例は y = a/x。a = xy = 4 × 6 = 24。', level: 3, category: '比例と反比例' },
  { id: 'm101', question: 'y = 20/x. Find x when y = 5.', answer: '4', unit: '', explanation: '5 = 20/x なので x = 20 ÷ 5 = 4。', level: 3, category: '比例と反比例' },
  { id: 'm102', question: 'The graph of y = ax passes through (2, 10). Find a.', answer: '5', unit: '', explanation: '10 = a × 2 なので a = 5。', level: 3, category: '比例と反比例' },
  { id: 'm103', question: 'If 6 workers finish a job in 10 days, how many days do 15 workers need at the same rate?', answer: '4', unit: 'days', explanation: '人数と日数は反比例。6 × 10 = 60、60 ÷ 15 = 4 日。', level: 3, category: '比例と反比例' },
  { id: 'm104', question: 'A rectangle is 8 cm long and 5 cm wide. What is its area in cm²?', answer: '40', unit: 'cm²', explanation: '長方形の面積 = 縦 × 横 = 8 × 5 = 40 cm²。', level: 1, category: '平面図形' },
  { id: 'm105', question: 'A rectangle is 8 cm long and 5 cm wide. What is its perimeter in cm?', answer: '26', unit: 'cm', explanation: '周の長さ = (縦 + 横) × 2 = (8 + 5) × 2 = 26 cm。', level: 1, category: '平面図形' },
  { id: 'm106', question: 'A square has a side of 7 cm. What is its area in cm²?', answer: '49', unit: 'cm²', explanation: '正方形の面積 = 1辺 × 1辺 = 7 × 7 = 49 cm²。', level: 1, category: '平面図形' },
  { id: 'm107', question: 'A circle has a radius of 5 cm. What is its diameter in cm?', answer: '10', unit: 'cm', explanation: '直径 = 半径 × 2 = 5 × 2 = 10 cm。', level: 1, category: '平面図形' },
  { id: 'm108', question: 'A triangle has a base of 10 cm and a height of 6 cm. What is its area in cm²?', answer: '30', unit: 'cm²', explanation: '三角形の面積 = 底辺 × 高さ ÷ 2 = 10 × 6 ÷ 2 = 30 cm²。', level: 2, category: '平面図形' },
  { id: 'm109', question: 'The angles of a triangle are 50° and 60°. What is the third angle in degrees?', answer: '70', unit: '°', explanation: '三角形の内角の和は 180°。180 − 50 − 60 = 70°。', level: 2, category: '平面図形' },
  { id: 'm110', question: 'Two angles on a straight line are 115° and x. What is x in degrees?', answer: '65', unit: '°', explanation: '直線上の角の和は 180°。180 − 115 = 65°。', level: 2, category: '平面図形' },
  { id: 'm111', question: 'A circle has a radius of 10 cm. What is its circumference in cm? Use π = 3.14.', answer: '62.8', unit: 'cm', explanation: '円周 = 2πr = 2 × 3.14 × 10 = 62.8 cm。', level: 2, category: '平面図形' },
  { id: 'm112', question: 'A circle has a radius of 5 cm. What is its area in cm²? Use π = 3.14.', answer: '78.5', unit: 'cm²', explanation: '円の面積 = πr² = 3.14 × 25 = 78.5 cm²。', level: 2, category: '平面図形' },
  { id: 'm113', question: 'A trapezoid has parallel sides of 6 cm and 10 cm, and a height of 5 cm. What is its area in cm²?', answer: '40', unit: 'cm²', explanation: '台形の面積 = (上底 + 下底) × 高さ ÷ 2 = 16 × 5 ÷ 2 = 40 cm²。', level: 2, category: '平面図形' },
  { id: 'm114', question: 'Two angles of a triangle are 90° and 35°. What is the third angle in degrees?', answer: '55', unit: '°', explanation: '内角の和は 180°。180 − 90 − 35 = 55°。', level: 2, category: '平面図形' },
  { id: 'm115', question: 'The area of a square is 81 cm². What is the length of one side in cm?', answer: '9', unit: 'cm', explanation: '9 × 9 = 81 なので 1辺は 9 cm。', level: 3, category: '平面図形' },
  { id: 'm116', question: 'A parallelogram has a base of 12 cm and a height of 7 cm. What is its area in cm²?', answer: '84', unit: 'cm²', explanation: '平行四辺形の面積 = 底辺 × 高さ = 12 × 7 = 84 cm²。', level: 3, category: '平面図形' },
  { id: 'm117', question: 'What is the sum of the interior angles of a quadrilateral, in degrees?', answer: '360', unit: '°', explanation: '四角形は三角形2つ分なので 180 × 2 = 360°。', level: 3, category: '平面図形' },
  { id: 'm118', question: 'A triangle has an area of 24 cm² and a base of 8 cm. What is its height in cm?', answer: '6', unit: 'cm', explanation: '面積 = 底辺 × 高さ ÷ 2 なので、高さ = 24 × 2 ÷ 8 = 6 cm。', level: 3, category: '平面図形' },
  { id: 'm119', question: 'A sector has a radius of 6 cm and a central angle of 90°. What is its area in cm²? Use π = 3.14.', answer: '28.26', unit: 'cm²', explanation: 'おうぎ形の面積 = πr² × 中心角/360 = 3.14 × 36 × 1/4 = 28.26 cm²。', level: 3, category: '平面図形' },
  { id: 'm120', question: 'A sector has a radius of 9 cm and a central angle of 120°. What is the length of its arc in cm? Use π = 3.14.', answer: '18.84', unit: 'cm', explanation: '弧の長さ = 2πr × 中心角/360 = 2 × 3.14 × 9 × 1/3 = 18.84 cm。', level: 3, category: '平面図形' },
  { id: 'm121', question: 'A rhombus has diagonals of 8 cm and 6 cm. What is its area in cm²?', answer: '24', unit: 'cm²', explanation: 'ひし形の面積 = 対角線 × 対角線 ÷ 2 = 8 × 6 ÷ 2 = 24 cm²。', level: 3, category: '平面図形' },
  { id: 'm122', question: 'What is the sum of the interior angles of a pentagon, in degrees?', answer: '540', unit: '°', explanation: 'n角形の内角の和 = (n − 2) × 180°。(5 − 2) × 180 = 540°。', level: 3, category: '平面図形' },
  { id: 'm123', question: 'A cube has a side of 4 cm. What is its volume in cm³?', answer: '64', unit: 'cm³', explanation: '立方体の体積 = 1辺³ = 4 × 4 × 4 = 64 cm³。', level: 2, category: '空間図形' },
  { id: 'm124', question: 'A box is 5 cm × 3 cm × 2 cm. What is its volume in cm³?', answer: '30', unit: 'cm³', explanation: '直方体の体積 = 縦 × 横 × 高さ = 5 × 3 × 2 = 30 cm³。', level: 2, category: '空間図形' },
  { id: 'm125', question: 'A rectangular prism is 6 cm × 4 cm × 5 cm. What is its volume in cm³?', answer: '120', unit: 'cm³', explanation: '直方体の体積 = 縦 × 横 × 高さ = 120 cm³。', level: 2, category: '空間図形' },
  { id: 'm126', question: 'A prism has a triangular base with an area of 12 cm² and a height of 7 cm. What is its volume in cm³?', answer: '84', unit: 'cm³', explanation: '角柱の体積 = 底面積 × 高さ = 12 × 7 = 84 cm³。', level: 2, category: '空間図形' },
  { id: 'm127', question: 'How many faces does a triangular prism have?', answer: '5', unit: '', explanation: '三角柱は底面2つ＋側面3つで 5 面。', level: 2, category: '空間図形' },
  { id: 'm128', question: 'How many edges does a cube have?', answer: '12', unit: '', explanation: '立方体の辺は 12 本。', level: 2, category: '空間図形' },
  { id: 'm129', question: 'A cylinder has a base radius of 4 cm. What is the area of its base in cm²? Use π = 3.14.', answer: '50.24', unit: 'cm²', explanation: '底面積 = πr² = 3.14 × 16 = 50.24 cm²。', level: 2, category: '空間図形' },
  { id: 'm130', question: 'A rectangular prism is 3 cm × 4 cm × 5 cm. What is its surface area in cm²?', answer: '94', unit: 'cm²', explanation: '表面積 = 2(縦×横 + 横×高 + 縦×高) = 2(12 + 20 + 15) = 94 cm²。', level: 3, category: '空間図形' },
  { id: 'm131', question: 'A cylinder has a base radius of 5 cm and a height of 10 cm. What is its volume in cm³? Use π = 3.14.', answer: '785', unit: 'cm³', explanation: '円柱の体積 = πr²h = 3.14 × 25 × 10 = 785 cm³。', level: 3, category: '空間図形' },
  { id: 'm132', question: 'A cone has a base radius of 3 cm and a height of 8 cm. What is its volume in cm³? Use π = 3.14.', answer: '75.36', unit: 'cm³', explanation: '円錐の体積 = πr²h ÷ 3 = 3.14 × 9 × 8 ÷ 3 = 75.36 cm³。', level: 3, category: '空間図形' },
  { id: 'm133', question: 'A pyramid has a square base of area 27 cm² and a height of 5 cm. What is its volume in cm³?', answer: '45', unit: 'cm³', explanation: '角錐の体積 = 底面積 × 高さ ÷ 3 = 27 × 5 ÷ 3 = 45 cm³。', level: 3, category: '空間図形' },
  { id: 'm134', question: 'Find the mean of 4, 7, 9, and 12.', answer: '8', unit: '', explanation: '合計 32 ÷ 個数 4 = 8。', level: 1, category: 'データの活用' },
  { id: 'm135', question: 'Find the median of 3, 8, 5, 11, 6.', answer: '6', unit: '', explanation: '小さい順に 3, 5, 6, 8, 11。真ん中は 6。', level: 2, category: 'データの活用' },
  { id: 'm136', question: 'Find the mode of 2, 5, 3, 5, 7, 5.', answer: '5', unit: '', explanation: '最も多く出てくる数は 5（3回）。', level: 2, category: 'データの活用' },
  { id: 'm137', question: 'Find the range of 14, 8, 21, 5.', answer: '16', unit: '', explanation: '範囲 = 最大 − 最小 = 21 − 5 = 16。', level: 2, category: 'データの活用' },
  { id: 'm138', question: 'In a class of 25, 60% are girls. How many girls are there?', answer: '15', unit: '', explanation: '25 × 0.6 = 15人。', level: 2, category: 'データの活用' },
  { id: 'm139', question: 'A class of 30 students has 12 who walk to school. What percentage walk? (Give the number only.)', answer: '40', unit: '', explanation: '12 ÷ 30 = 0.4 なので 40%。', level: 2, category: 'データの活用' },
  { id: 'm140', question: 'Find the mean of 6, 9, 11, 14, and 20.', answer: '12', unit: '', explanation: '合計 60 ÷ 5 = 12。', level: 2, category: 'データの活用' },
  { id: 'm141', question: 'A class scored these marks: 7, 8, 8, 9, 10. What is the range?', answer: '3', unit: '', explanation: '範囲 = 最大 − 最小 = 10 − 7 = 3。', level: 2, category: 'データの活用' },
  { id: 'm142', question: 'A coin is flipped once. What is the probability of getting heads? Write it as a decimal.', answer: '0.5', unit: '', explanation: '表と裏の2通りのうち1通り。1 ÷ 2 = 0.5。', level: 2, category: 'データの活用' },
  { id: 'm143', question: 'A bag has 3 red and 5 blue balls. What is the probability of picking a red one? Write it as a decimal.', answer: '0.375', unit: '', explanation: '全部で 8 個のうち赤は 3 個。3 ÷ 8 = 0.375。', level: 3, category: 'データの活用' },
  { id: 'm144', question: 'A die is rolled once. What is the probability of getting a number greater than 4? Write it as a decimal to two places.', answer: '0.33', unit: '', explanation: '5 と 6 の 2 通り。2 ÷ 6 = 0.333… なので小数第2位で 0.33。', level: 3, category: 'データの活用' },
  { id: 'm145', question: 'The mean of 5 numbers is 12. One number is removed and the mean becomes 13. What number was removed?', answer: '8', unit: '', explanation: '元の合計は 60、残り4個の合計は 52。60 − 52 = 8。', level: 3, category: 'データの活用' },
  { id: 'm146', question: 'In a frequency table, 8 students scored 60–69 out of 40 students in total. What is the relative frequency? Write it as a decimal.', answer: '0.2', unit: '', explanation: '相対度数 = その階級の度数 ÷ 全体 = 8 ÷ 40 = 0.2。', level: 3, category: 'データの活用' },
  { id: 'm147', question: 'The class sizes are 5, 8, 12, and 15. What is the cumulative frequency of the first three classes?', answer: '25', unit: '', explanation: '累積度数は小さい階級から順に足す。5 + 8 + 12 = 25。', level: 3, category: 'データの活用' },
  { id: 'm148', question: 'Find the median of 4, 9, 2, 7, 12, 5.', answer: '6', unit: '', explanation: '小さい順に 2,4,5,7,9,12。個数が偶数なので中央2つの平均 (5+7)÷2 = 6。', level: 3, category: 'データの活用' },
  { id: 'm149', question: 'In a frequency table, the class 10–20 has a midpoint (class value). What is it?', answer: '15', unit: '', explanation: '階級値は階級の真ん中の値。(10 + 20) ÷ 2 = 15。', level: 3, category: 'データの活用' }
];

// 単元の並び順（小学の復習 → 中1）
const MATH_CATEGORIES = [...new Set(MATH_DATA.map((p) => p.category))];
