/**
 * 熟語・句動詞（英検3級〜2級）。
 *
 * 辞書データから熟語を取ろうとしたが、ejdict の複数語見出しは固有名詞や俗語が
 * 中心で使えず、CEFR-J の複数語も bus stop のような複合名詞ばかりだったため、
 * ここは手で書いている。全件に例文と和訳を付けてある。
 *
 *   level 2 = 英検3級 / level 3 = 英検準2級 / level 4 = 英検2級
 *
 * tools/build-vocab.mjs がこれを読み込んで js/data.js に混ぜる。
 * pos は 'phr.'、category は '熟語・句動詞' が自動で入る。
 */
export const IDIOMS = [
  // ---------- 英検3級レベル（level 2） ----------
  { word: 'look for', meaning: 'を探す', level: 2, example: 'I am looking for my keys.', exampleJa: '私は鍵を探している。' },
  { word: 'look at', meaning: 'を見る', level: 2, example: 'Look at this picture.', exampleJa: 'この写真を見て。' },
  { word: 'look after', meaning: 'の世話をする', level: 2, example: 'She looks after her little brother.', exampleJa: '彼女は弟の世話をしている。' },
  { word: 'look forward to', meaning: 'を楽しみに待つ', level: 3, example: 'I look forward to seeing you again.', exampleJa: 'またお会いできるのを楽しみにしています。' },
  { word: 'get up', meaning: '起きる', level: 2, example: 'I get up at six every morning.', exampleJa: '私は毎朝6時に起きる。' },
  { word: 'get on', meaning: 'に乗る', level: 2, example: 'Get on the bus at the next stop.', exampleJa: '次の停留所でバスに乗って。' },
  { word: 'get off', meaning: 'から降りる', level: 2, example: 'We got off the train at Bangkok.', exampleJa: '私たちはバンコクで電車を降りた。' },
  { word: 'get to', meaning: 'に着く', level: 2, example: 'What time did you get to school?', exampleJa: '何時に学校に着きましたか。' },
  { word: 'take care of', meaning: 'の世話をする', level: 2, example: 'Please take care of my dog.', exampleJa: '私の犬の世話をしてください。' },
  { word: 'take off', meaning: 'を脱ぐ、離陸する', level: 2, example: 'Please take off your shoes here.', exampleJa: 'ここで靴を脱いでください。' },
  { word: 'take part in', meaning: 'に参加する', level: 3, example: 'She took part in the speech contest.', exampleJa: '彼女はスピーチコンテストに参加した。' },
  { word: 'take a walk', meaning: '散歩する', level: 2, example: 'We took a walk in the park.', exampleJa: '私たちは公園を散歩した。' },
  { word: 'put on', meaning: 'を身につける', level: 2, example: 'Put on your jacket. It is cold.', exampleJa: '上着を着なさい。寒いよ。' },
  { word: 'put off', meaning: 'を延期する', level: 3, example: 'They put off the meeting until Friday.', exampleJa: '彼らは会議を金曜まで延期した。' },
  { word: 'turn on', meaning: 'をつける', level: 2, example: 'Turn on the light, please.', exampleJa: '電気をつけてください。' },
  { word: 'turn off', meaning: 'を消す', level: 2, example: 'Do not forget to turn off the TV.', exampleJa: 'テレビを消すのを忘れないで。' },
  { word: 'give up', meaning: 'をあきらめる', level: 2, example: 'Never give up your dream.', exampleJa: '夢をあきらめてはいけない。' },
  { word: 'come from', meaning: '出身である', level: 2, example: 'She comes from Thailand.', exampleJa: '彼女はタイの出身だ。' },
  { word: 'come back', meaning: '戻ってくる', level: 2, example: 'He will come back next week.', exampleJa: '彼は来週戻ってくる。' },
  { word: 'go out', meaning: '外出する', level: 2, example: 'We went out for dinner.', exampleJa: '私たちは夕食に出かけた。' },
  { word: 'go on', meaning: '続く、続ける', level: 2, example: 'The concert went on for two hours.', exampleJa: 'コンサートは2時間続いた。' },
  { word: 'wake up', meaning: '目を覚ます', level: 2, example: 'I woke up early this morning.', exampleJa: '私は今朝早く目が覚めた。' },
  { word: 'stand up', meaning: '立ち上がる', level: 2, example: 'Everyone stood up when she entered.', exampleJa: '彼女が入ってくると全員が立ち上がった。' },
  { word: 'sit down', meaning: '座る', level: 2, example: 'Please sit down and wait.', exampleJa: '座ってお待ちください。' },
  { word: 'listen to', meaning: 'を聞く', level: 2, example: 'I listen to music every day.', exampleJa: '私は毎日音楽を聞く。' },
  { word: 'wait for', meaning: 'を待つ', level: 2, example: 'She is waiting for the bus.', exampleJa: '彼女はバスを待っている。' },
  { word: 'arrive at', meaning: 'に到着する', level: 2, example: 'We arrived at the airport at noon.', exampleJa: '私たちは正午に空港に着いた。' },
  { word: 'be good at', meaning: 'が得意である', level: 2, example: 'He is good at math.', exampleJa: '彼は数学が得意だ。' },
  { word: 'be interested in', meaning: 'に興味がある', level: 2, example: 'I am interested in science.', exampleJa: '私は理科に興味がある。' },
  { word: 'be famous for', meaning: 'で有名である', level: 2, example: 'This town is famous for its temples.', exampleJa: 'この町は寺で有名だ。' },
  { word: 'be different from', meaning: 'と異なる', level: 2, example: 'His idea is different from mine.', exampleJa: '彼の考えは私のとは違う。' },
  { word: 'be full of', meaning: 'でいっぱいである', level: 2, example: 'The box was full of books.', exampleJa: '箱は本でいっぱいだった。' },
  { word: 'be afraid of', meaning: 'を恐れる', level: 2, example: 'My sister is afraid of dogs.', exampleJa: '妹は犬を怖がる。' },
  { word: 'be proud of', meaning: 'を誇りに思う', level: 3, example: 'I am proud of my school.', exampleJa: '私は自分の学校を誇りに思う。' },
  { word: 'be able to', meaning: 'できる', level: 2, example: 'She was able to solve the problem.', exampleJa: '彼女はその問題を解くことができた。' },
  { word: 'a lot of', meaning: 'たくさんの', level: 2, example: 'There are a lot of people here.', exampleJa: 'ここにはたくさんの人がいる。' },
  { word: 'a few', meaning: '少しの', level: 2, example: 'I have a few questions.', exampleJa: '質問がいくつかあります。' },
  { word: 'a little', meaning: '少しの', level: 2, example: 'Add a little salt.', exampleJa: '塩を少し加えて。' },
  { word: 'of course', meaning: 'もちろん', level: 2, example: 'Of course you can join us.', exampleJa: 'もちろん参加していいよ。' },
  { word: 'for example', meaning: 'たとえば', level: 2, example: 'Some animals, for example bees, are very useful.', exampleJa: 'たとえばハチのように、役に立つ動物もいる。' },
  { word: 'at first', meaning: '最初は', level: 2, example: 'At first the work was difficult.', exampleJa: '最初その作業は難しかった。' },
  { word: 'at last', meaning: 'ついに', level: 2, example: 'At last we reached the top.', exampleJa: 'ついに私たちは頂上に着いた。' },
  { word: 'all day', meaning: '一日中', level: 2, example: 'It rained all day.', exampleJa: '一日中雨が降った。' },
  { word: 'right now', meaning: '今すぐ', level: 2, example: 'I need your help right now.', exampleJa: '今すぐ手伝ってほしい。' },
  { word: 'each other', meaning: 'お互いに', level: 2, example: 'They helped each other.', exampleJa: '彼らは互いに助け合った。' },
  { word: 'over there', meaning: 'あそこに', level: 2, example: 'The library is over there.', exampleJa: '図書館はあそこです。' },
  { word: 'far from', meaning: 'から遠い', level: 2, example: 'The station is far from my house.', exampleJa: '駅は家から遠い。' },
  { word: 'next to', meaning: 'の隣に', level: 2, example: 'She sat next to me.', exampleJa: '彼女は私の隣に座った。' },
  { word: 'in the middle of', meaning: 'の真ん中に、の最中に', level: 3, example: 'He woke up in the middle of the night.', exampleJa: '彼は夜中に目を覚ました。' },
  { word: 'how about', meaning: 'はどうですか', level: 2, example: 'How about going to the museum?', exampleJa: '博物館に行くのはどう。' },
  { word: 'would like to', meaning: 'したい', level: 2, example: 'I would like to visit Kyoto.', exampleJa: '私は京都を訪れたい。' },
  { word: 'have to', meaning: 'しなければならない', level: 2, example: 'You have to finish your homework.', exampleJa: '宿題を終わらせなければならない。' },
  { word: "don't have to", meaning: 'する必要がない', level: 2, example: 'You do not have to come early.', exampleJa: '早く来る必要はありません。' },
  { word: 'had better', meaning: 'したほうがよい', level: 3, example: 'You had better see a doctor.', exampleJa: '医者に診てもらったほうがいい。' },
  { word: 'used to', meaning: '以前はよくした', level: 3, example: 'I used to play the piano.', exampleJa: '私は昔ピアノを弾いていた。' },
  { word: 'be going to', meaning: 'するつもりだ', level: 2, example: 'We are going to study abroad.', exampleJa: '私たちは留学するつもりだ。' },
  { word: 'want to', meaning: 'したい', level: 2, example: 'I want to be a teacher.', exampleJa: '私は先生になりたい。' },
  { word: 'try to', meaning: 'しようとする', level: 2, example: 'He tried to open the door.', exampleJa: '彼はドアを開けようとした。' },
  { word: 'begin to', meaning: 'し始める', level: 2, example: 'It began to rain.', exampleJa: '雨が降り始めた。' },
  { word: 'stop doing', meaning: 'するのをやめる', level: 2, example: 'Please stop talking during class.', exampleJa: '授業中は話すのをやめてください。' },
  { word: 'enjoy doing', meaning: 'するのを楽しむ', level: 2, example: 'They enjoyed swimming in the sea.', exampleJa: '彼らは海で泳ぐのを楽しんだ。' },
  { word: 'finish doing', meaning: 'し終える', level: 2, example: 'I finished reading the book.', exampleJa: '私はその本を読み終えた。' },
  { word: 'thank you for', meaning: 'をありがとう', level: 2, example: 'Thank you for your help.', exampleJa: '手伝ってくれてありがとう。' },
  { word: 'help with', meaning: 'を手伝う', level: 2, example: 'Can you help me with my homework?', exampleJa: '宿題を手伝ってくれますか。' },
  { word: 'go to bed', meaning: '寝る', level: 2, example: 'I go to bed at ten.', exampleJa: '私は10時に寝る。' },
  { word: 'go shopping', meaning: '買い物に行く', level: 2, example: 'We went shopping yesterday.', exampleJa: '私たちは昨日買い物に行った。' },
  { word: 'have a good time', meaning: '楽しい時を過ごす', level: 2, example: 'We had a good time at the festival.', exampleJa: '私たちは祭りで楽しい時を過ごした。' },
  { word: 'take a picture', meaning: '写真を撮る', level: 2, example: 'He took a picture of the temple.', exampleJa: '彼は寺の写真を撮った。' },
  { word: 'get married', meaning: '結婚する', level: 3, example: 'They got married last spring.', exampleJa: '彼らは去年の春に結婚した。' },
  { word: 'be born', meaning: '生まれる', level: 2, example: 'She was born in Thailand.', exampleJa: '彼女はタイで生まれた。' },
  { word: 'grow up', meaning: '成長する', level: 2, example: 'I grew up in a small village.', exampleJa: '私は小さな村で育った。' },
  { word: 'find out', meaning: 'を見つけ出す', level: 3, example: 'We found out the truth later.', exampleJa: '私たちは後で真実を知った。' },
  { word: 'hear about', meaning: 'について聞く', level: 2, example: 'Did you hear about the new teacher?', exampleJa: '新しい先生のこと聞いた。' },
  { word: 'talk about', meaning: 'について話す', level: 2, example: 'They talked about the trip.', exampleJa: '彼らは旅行について話した。' },
  { word: 'think about', meaning: 'について考える', level: 2, example: 'Think about it carefully.', exampleJa: 'よく考えてみて。' },
  { word: 'worry about', meaning: 'を心配する', level: 2, example: 'Do not worry about the test.', exampleJa: 'テストのことを心配しないで。' },
  { word: 'write to', meaning: 'に手紙を書く', level: 2, example: 'She wrote to her friend in Japan.', exampleJa: '彼女は日本の友達に手紙を書いた。' },
  { word: 'belong to', meaning: 'に所属する', level: 3, example: 'He belongs to the tennis club.', exampleJa: '彼はテニス部に所属している。' },

  // ---------- 英検準2級レベル（level 3） ----------
  { word: 'according to', meaning: 'によれば', level: 3, example: 'According to the report, sales increased.', exampleJa: '報告によれば売り上げは増えた。' },
  { word: 'because of', meaning: 'のために', level: 3, example: 'The game was canceled because of rain.', exampleJa: '雨のため試合は中止になった。' },
  { word: 'instead of', meaning: 'の代わりに', level: 3, example: 'She drank tea instead of coffee.', exampleJa: '彼女はコーヒーの代わりに紅茶を飲んだ。' },
  { word: 'in front of', meaning: 'の前に', level: 3, example: 'A car stopped in front of the house.', exampleJa: '家の前に車が止まった。' },
  { word: 'in order to', meaning: 'するために', level: 3, example: 'He studied hard in order to pass the exam.', exampleJa: '彼は試験に受かるために猛勉強した。' },
  { word: 'as soon as', meaning: 'するとすぐに', level: 3, example: 'Call me as soon as you arrive.', exampleJa: '着いたらすぐ電話して。' },
  { word: 'as well as', meaning: 'と同様に', level: 3, example: 'She speaks French as well as English.', exampleJa: '彼女は英語だけでなくフランス語も話す。' },
  { word: 'so that', meaning: 'するように', level: 3, example: 'Speak slowly so that everyone can understand.', exampleJa: 'みんなが分かるようにゆっくり話して。' },
  { word: 'such as', meaning: 'のような', level: 3, example: 'I like sports such as soccer and tennis.', exampleJa: '私はサッカーやテニスのようなスポーツが好きだ。' },
  { word: 'more than', meaning: 'より多い', level: 3, example: 'More than fifty students joined.', exampleJa: '50人を超える生徒が参加した。' },
  { word: 'no longer', meaning: 'もはやしない', level: 3, example: 'He no longer lives here.', exampleJa: '彼はもうここには住んでいない。' },
  { word: 'at least', meaning: '少なくとも', level: 3, example: 'Sleep at least eight hours.', exampleJa: '少なくとも8時間は寝なさい。' },
  { word: 'at the same time', meaning: '同時に', level: 3, example: 'They finished at the same time.', exampleJa: '彼らは同時に終えた。' },
  { word: 'in fact', meaning: '実際は', level: 3, example: 'In fact, the story is true.', exampleJa: '実際、その話は本当だ。' },
  { word: 'as a result', meaning: 'その結果', level: 3, example: 'As a result, prices went up.', exampleJa: 'その結果、価格が上がった。' },
  { word: 'on the other hand', meaning: '一方で', level: 3, example: 'On the other hand, some people disagree.', exampleJa: '一方で、反対する人もいる。' },
  { word: 'in addition', meaning: 'さらに', level: 3, example: 'In addition, the hotel offers free breakfast.', exampleJa: 'さらにそのホテルは朝食を無料で出す。' },
  { word: 'for a while', meaning: 'しばらくの間', level: 3, example: 'Let us rest for a while.', exampleJa: 'しばらく休もう。' },
  { word: 'these days', meaning: '最近', level: 3, example: 'These days many students study online.', exampleJa: '最近は多くの生徒がオンラインで学ぶ。' },
  { word: 'from now on', meaning: 'これからは', level: 3, example: 'From now on I will study every day.', exampleJa: 'これからは毎日勉強します。' },
  { word: 'once in a while', meaning: 'たまに', level: 4, example: 'We eat out once in a while.', exampleJa: '私たちはたまに外食する。' },
  { word: 'as usual', meaning: 'いつものように', level: 3, example: 'As usual, he arrived late.', exampleJa: 'いつものように彼は遅れて来た。' },
  { word: 'be based on', meaning: 'に基づいている', level: 4, example: 'The movie is based on a true story.', exampleJa: 'その映画は実話に基づいている。' },
  { word: 'be covered with', meaning: 'で覆われている', level: 3, example: 'The mountain was covered with snow.', exampleJa: '山は雪で覆われていた。' },
  { word: 'be filled with', meaning: 'で満たされている', level: 3, example: 'The hall was filled with music.', exampleJa: 'ホールは音楽で満たされていた。' },
  { word: 'be known for', meaning: 'で知られている', level: 3, example: 'The city is known for its markets.', exampleJa: 'その都市は市場で知られている。' },
  { word: 'be made of', meaning: 'でできている', level: 3, example: 'This box is made of wood.', exampleJa: 'この箱は木でできている。' },
  { word: 'be similar to', meaning: 'に似ている', level: 3, example: "Her voice is similar to her mother's.", exampleJa: '彼女の声は母親に似ている。' },
  { word: 'be responsible for', meaning: 'に責任がある', level: 4, example: 'Who is responsible for this project?', exampleJa: 'この企画は誰が責任者ですか。' },
  { word: 'be used to', meaning: 'に慣れている', level: 3, example: 'She is used to speaking English.', exampleJa: '彼女は英語を話すことに慣れている。' },
  { word: 'be worried about', meaning: 'を心配している', level: 3, example: 'They are worried about the weather.', exampleJa: '彼らは天気を心配している。' },
  { word: 'be surprised at', meaning: 'に驚く', level: 3, example: 'I was surprised at the news.', exampleJa: '私はその知らせに驚いた。' },
  { word: 'be satisfied with', meaning: 'に満足している', level: 4, example: 'He is satisfied with the result.', exampleJa: '彼は結果に満足している。' },
  { word: 'be about to', meaning: 'まさにしようとしている', level: 4, example: 'The train is about to leave.', exampleJa: '電車はまさに出発しようとしている。' },
  { word: 'be supposed to', meaning: 'することになっている', level: 4, example: 'We are supposed to meet at seven.', exampleJa: '私たちは7時に会うことになっている。' },
  { word: 'be likely to', meaning: 'しそうである', level: 4, example: 'It is likely to rain tomorrow.', exampleJa: '明日は雨が降りそうだ。' },
  { word: 'be willing to', meaning: '喜んでする', level: 4, example: 'She is willing to help us.', exampleJa: '彼女は喜んで手伝ってくれる。' },
  { word: 'give in', meaning: '屈する', level: 4, example: 'He never gives in to pressure.', exampleJa: '彼は圧力に決して屈しない。' },
  { word: 'bring up', meaning: 'を育てる、を持ち出す', level: 4, example: 'She was brought up by her grandmother.', exampleJa: '彼女は祖母に育てられた。' },
  { word: 'call off', meaning: 'を中止する', level: 4, example: 'They called off the concert.', exampleJa: '彼らはコンサートを中止した。' },
  { word: 'carry out', meaning: 'を実行する', level: 4, example: 'The team carried out the experiment.', exampleJa: 'チームは実験を実行した。' },
  { word: 'check in', meaning: '搭乗手続きをする', level: 3, example: 'Please check in two hours before departure.', exampleJa: '出発の2時間前に手続きをしてください。' },
  { word: 'come across', meaning: '偶然出会う', level: 4, example: 'I came across an old friend downtown.', exampleJa: '街で偶然旧友に会った。' },
  { word: 'come true', meaning: '実現する', level: 3, example: 'Her dream came true at last.', exampleJa: '彼女の夢はついに実現した。' },
  { word: 'count on', meaning: 'を頼りにする', level: 4, example: 'You can count on me.', exampleJa: '私を頼っていいよ。' },
  { word: 'deal with', meaning: 'に対処する', level: 4, example: 'We must deal with this problem now.', exampleJa: '今この問題に対処しなければならない。' },
  { word: 'depend on', meaning: 'に頼る、次第である', level: 3, example: 'It depends on the weather.', exampleJa: 'それは天気次第だ。' },
  { word: 'figure out', meaning: 'を理解する、を解き明かす', level: 4, example: 'I could not figure out the answer.', exampleJa: '私は答えが分からなかった。' },
  { word: 'fill in', meaning: 'に記入する', level: 3, example: 'Fill in your name and address.', exampleJa: '名前と住所を記入してください。' },
  { word: 'get along with', meaning: 'と仲良くする', level: 4, example: 'She gets along with everyone.', exampleJa: '彼女は誰とでも仲良くする。' },
  { word: 'get over', meaning: 'を乗り越える', level: 4, example: 'It took him a month to get over the cold.', exampleJa: '風邪が治るのに1か月かかった。' },
  { word: 'get rid of', meaning: 'を取り除く', level: 4, example: 'We need to get rid of these old books.', exampleJa: 'この古い本を処分する必要がある。' },
  { word: 'give away', meaning: 'をただで与える', level: 4, example: 'The store gave away free samples.', exampleJa: '店は試供品を無料で配った。' },
  { word: 'hand in', meaning: 'を提出する', level: 3, example: 'Hand in your report by Friday.', exampleJa: '金曜までにレポートを提出しなさい。' },
  { word: 'hang up', meaning: '電話を切る', level: 3, example: 'She hung up before I could answer.', exampleJa: '私が答える前に彼女は電話を切った。' },
  { word: 'keep in touch', meaning: '連絡を取り合う', level: 4, example: 'Let us keep in touch after graduation.', exampleJa: '卒業後も連絡を取り合おう。' },
  { word: 'keep on', meaning: 'し続ける', level: 3, example: 'He kept on running to the end.', exampleJa: '彼は最後まで走り続けた。' },
  { word: 'look up', meaning: 'を調べる', level: 3, example: 'Look up the word in a dictionary.', exampleJa: 'その語を辞書で調べなさい。' },
  { word: 'make sure', meaning: '確かめる', level: 3, example: 'Make sure the door is locked.', exampleJa: 'ドアに鍵がかかっているか確かめて。' },
  { word: "make up one's mind", meaning: '決心する', level: 4, example: 'He made up his mind to study abroad.', exampleJa: '彼は留学する決心をした。' },
  { word: 'pay attention to', meaning: 'に注意を払う', level: 4, example: 'Pay attention to the teacher.', exampleJa: '先生の話に注意しなさい。' },
  { word: 'pick up', meaning: 'を拾う、を迎えに行く', level: 3, example: 'I will pick you up at the station.', exampleJa: '駅まで迎えに行くよ。' },
  { word: 'point out', meaning: 'を指摘する', level: 4, example: 'She pointed out my mistake.', exampleJa: '彼女は私の誤りを指摘した。' },
  { word: 'put up with', meaning: 'を我慢する', level: 4, example: 'I cannot put up with this noise.', exampleJa: 'この騒音には我慢できない。' },
  { word: 'run out of', meaning: 'を使い果たす', level: 4, example: 'We ran out of water on the second day.', exampleJa: '2日目に水を使い果たした。' },
  { word: 'set up', meaning: 'を設立する、を組み立てる', level: 4, example: 'They set up a new company.', exampleJa: '彼らは新しい会社を設立した。' },
  { word: 'show up', meaning: '現れる', level: 4, example: 'He did not show up at the party.', exampleJa: '彼はパーティーに現れなかった。' },
  { word: 'take place', meaning: '行われる', level: 3, example: 'The ceremony takes place in March.', exampleJa: '式は3月に行われる。' },
  { word: 'take over', meaning: 'を引き継ぐ', level: 4, example: 'She took over the family business.', exampleJa: '彼女は家業を引き継いだ。' },
  { word: 'throw away', meaning: 'を捨てる', level: 3, example: 'Do not throw away plastic bags.', exampleJa: 'ビニール袋を捨てないで。' },
  { word: 'turn out', meaning: 'であると分かる', level: 4, example: 'The rumor turned out to be false.', exampleJa: 'そのうわさは誤りだと分かった。' },
  { word: 'work on', meaning: 'に取り組む', level: 3, example: 'She is working on a new project.', exampleJa: '彼女は新しい企画に取り組んでいる。' },
  { word: 'give a hand', meaning: '手を貸す', level: 3, example: 'Could you give me a hand?', exampleJa: '手を貸してもらえますか。' },
  { word: 'make a difference', meaning: '違いを生む', level: 4, example: 'Small actions can make a difference.', exampleJa: '小さな行動が違いを生むことがある。' },
  { word: 'in other words', meaning: '言い換えれば', level: 4, example: 'In other words, we need more time.', exampleJa: '言い換えれば、もっと時間が必要だ。' },
  { word: 'above all', meaning: '何よりも', level: 4, example: 'Above all, stay safe.', exampleJa: '何よりも安全でいてください。' },
  { word: 'after all', meaning: '結局', level: 3, example: 'After all, she decided to go.', exampleJa: '結局、彼女は行くことにした。' },
  { word: 'by the way', meaning: 'ところで', level: 3, example: 'By the way, did you finish the report?', exampleJa: 'ところで、報告書は終わった。' },
  { word: 'in spite of', meaning: 'にもかかわらず', level: 4, example: 'In spite of the rain, they played.', exampleJa: '雨にもかかわらず彼らは試合をした。' },
  { word: 'thanks to', meaning: 'のおかげで', level: 3, example: 'Thanks to your advice, I passed.', exampleJa: '助言のおかげで合格しました。' },
  { word: 'due to', meaning: 'が原因で', level: 4, example: 'The delay was due to heavy snow.', exampleJa: '遅れは大雪が原因だった。' },
  { word: 'as long as', meaning: 'する限り', level: 4, example: 'You may stay as long as you like.', exampleJa: '好きなだけいていいですよ。' },
  { word: 'even if', meaning: 'たとえしても', level: 3, example: 'Even if it rains, we will go.', exampleJa: 'たとえ雨でも私たちは行く。' },
  { word: 'not only', meaning: 'だけでなく', level: 4, example: 'She is not only kind but also smart.', exampleJa: '彼女は親切なだけでなく賢い。' },
  { word: 'the number of', meaning: 'の数', level: 3, example: 'The number of students is increasing.', exampleJa: '生徒の数が増えている。' },
  { word: 'a number of', meaning: 'いくつかの', level: 3, example: 'A number of people were waiting.', exampleJa: '何人かの人が待っていた。' },
  { word: 'plenty of', meaning: 'たくさんの', level: 3, example: 'We have plenty of time.', exampleJa: '時間はたっぷりある。' },
  { word: 'most of', meaning: 'のほとんど', level: 2, example: 'Most of the students agreed.', exampleJa: '生徒のほとんどが賛成した。' },
  { word: 'both of', meaning: '両方とも', level: 2, example: 'Both of them are my friends.', exampleJa: '彼ら二人とも私の友達だ。' },
  { word: 'on time', meaning: '時間どおりに', level: 3, example: 'The train arrived on time.', exampleJa: '電車は時間どおりに着いた。' },
  { word: 'in time', meaning: '間に合って', level: 3, example: 'We got there in time for the show.', exampleJa: 'ショーに間に合って着いた。' },
  { word: 'take a break', meaning: '休憩する', level: 3, example: 'Let us take a break for ten minutes.', exampleJa: '10分休憩しよう。' },
  { word: 'in general', meaning: '一般に', level: 4, example: 'In general, children learn languages quickly.', exampleJa: '一般に子供は言語を早く覚える。' },
  { word: 'for instance', meaning: 'たとえば', level: 4, example: 'For instance, consider this case.', exampleJa: 'たとえばこの場合を考えてみよう。' },
  { word: 'so far', meaning: '今までのところ', level: 3, example: 'So far everything is fine.', exampleJa: '今のところすべて順調だ。' },
  { word: 'all over the world', meaning: '世界中で', level: 2, example: 'This song is loved all over the world.', exampleJa: 'この歌は世界中で愛されている。' },
  { word: 'more and more', meaning: 'ますます多くの', level: 3, example: 'More and more people use bicycles.', exampleJa: 'ますます多くの人が自転車を使う。' },
  { word: 'one another', meaning: 'お互いに', level: 3, example: 'The team members trust one another.', exampleJa: 'チームの仲間は互いを信頼している。' },
  { word: 'first of all', meaning: 'まず第一に', level: 3, example: 'First of all, read the question carefully.', exampleJa: 'まず第一に問題をよく読みなさい。' },
  { word: 'in the end', meaning: '最終的に', level: 3, example: 'In the end they reached an agreement.', exampleJa: '最終的に彼らは合意に達した。' },
  { word: 'no matter what', meaning: '何があろうと', level: 4, example: 'No matter what happens, keep trying.', exampleJa: '何があっても挑戦し続けなさい。' },
  { word: 'take advantage of', meaning: 'を利用する', level: 4, example: 'Take advantage of this chance.', exampleJa: 'この機会を利用しなさい。' },
  { word: 'be aware of', meaning: 'に気づいている', level: 4, example: 'Are you aware of the risk?', exampleJa: 'その危険に気づいていますか。' },
  { word: 'in charge of', meaning: 'を担当して', level: 4, example: 'She is in charge of the library.', exampleJa: '彼女は図書室を担当している。' },
  { word: 'on purpose', meaning: 'わざと', level: 4, example: 'He did not break it on purpose.', exampleJa: '彼はわざと壊したのではない。' },
  { word: 'come up with', meaning: 'を思いつく', level: 4, example: 'She came up with a good idea.', exampleJa: '彼女はよい考えを思いついた。' },
  { word: 'look up to', meaning: 'を尊敬する', level: 4, example: 'Many students look up to her.', exampleJa: '多くの生徒が彼女を尊敬している。' },
  { word: 'give it a try', meaning: 'やってみる', level: 3, example: 'It looks hard, but give it a try.', exampleJa: '難しそうだけど、やってみて。' },
  { word: 'be tired of', meaning: 'に飽きている', level: 3, example: 'I am tired of eating the same food.', exampleJa: '同じ食べ物に飽きた。' },
  { word: 'be short of', meaning: 'が不足している', level: 4, example: 'We are short of time.', exampleJa: '時間が足りない。' },
  { word: 'take care', meaning: '気をつける', level: 2, example: 'Take care on your way home.', exampleJa: '帰り道気をつけてね。' },
  { word: 'get in touch with', meaning: 'と連絡を取る', level: 4, example: 'Please get in touch with me later.', exampleJa: '後で連絡してください。' },
  { word: 'be capable of', meaning: 'ができる', level: 4, example: 'She is capable of solving it alone.', exampleJa: '彼女は一人でそれを解決できる。' },
  { word: 'result in', meaning: 'という結果になる', level: 4, example: 'The accident resulted in a long delay.', exampleJa: '事故は長い遅延という結果になった。' },
  { word: 'lead to', meaning: 'につながる', level: 4, example: 'Hard work leads to success.', exampleJa: '努力は成功につながる。' },
  { word: 'contribute to', meaning: 'に貢献する', level: 4, example: 'Trees contribute to clean air.', exampleJa: '木はきれいな空気に貢献する。' },
  { word: 'focus on', meaning: 'に集中する', level: 4, example: 'Focus on one thing at a time.', exampleJa: '一度に一つのことに集中しなさい。' },
  { word: 'consist of', meaning: 'から成る', level: 4, example: 'The team consists of ten members.', exampleJa: 'チームは10人から成る。' },
  { word: 'refer to', meaning: 'に言及する、を参照する', level: 4, example: 'Refer to page twenty for details.', exampleJa: '詳細は20ページを参照。' },
  { word: 'apply for', meaning: 'に応募する', level: 4, example: 'He applied for a scholarship.', exampleJa: '彼は奨学金に応募した。' },
  { word: 'succeed in', meaning: 'に成功する', level: 4, example: 'They succeeded in reaching the summit.', exampleJa: '彼らは登頂に成功した。' },
  { word: 'be exposed to', meaning: 'にさらされる', level: 4, example: 'Children are exposed to many languages here.', exampleJa: 'ここでは子供が多くの言語に触れる。' },
  { word: 'take notice of', meaning: 'に注目する', level: 4, example: 'Few people took notice of the sign.', exampleJa: 'その標識に気づいた人は少なかった。' },
  { word: 'make an effort', meaning: '努力する', level: 4, example: 'She made an effort to speak clearly.', exampleJa: '彼女ははっきり話す努力をした。' },
  { word: 'in danger of', meaning: 'の危険がある', level: 4, example: 'The species is in danger of dying out.', exampleJa: 'その種は絶滅の危険がある。' },
  { word: 'be equal to', meaning: 'と等しい', level: 3, example: 'One kilometer is equal to a thousand meters.', exampleJa: '1キロメートルは1000メートルに等しい。' }
];
